In [108]:
pip install pandas

Requirement already satisfied: pandas in c:\users\alirm\documents\venvs\ml_venv\lib\site-packages (2.3.3)
Requirement already satisfied: pytz>=2020.1 in c:\users\alirm\documents\venvs\ml_venv\lib\site-packages (from pandas) (2026.3.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\alirm\documents\venvs\ml_venv\lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: numpy>=1.22.4 in c:\users\alirm\documents\venvs\ml_venv\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\alirm\documents\venvs\ml_venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\alirm\documents\venvs\ml_venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [109]:
import pandas as pd

In [110]:
train_data = pd.read_csv('train.csv')

In [111]:
train_data = train_data[['Id', 'GrLivArea', 'SalePrice']]

In [112]:
train_data.head()

   Id  GrLivArea  SalePrice
0   1       1710     208500
1   2       1262     181500
2   3       1786     223500
3   4       1717     140000
4   5       2198     250000

In [113]:
train_data.describe()

                Id    GrLivArea      SalePrice
count  1460.000000  1460.000000    1460.000000
mean    730.500000  1515.463699  180921.195890
std     421.610009   525.480383   79442.502883
min       1.000000   334.000000   34900.000000
25%     365.750000  1129.500000  129975.000000
50%     730.500000  1464.000000  163000.000000
75%    1095.250000  1776.750000  214000.000000
max    1460.000000  5642.000000  755000.000000

In [114]:
split_at = int(0.8 * len(train_data))

train_rows = train_data.iloc[:split_at]
validation_rows = train_data.iloc[split_at:]


x_train = train_rows['GrLivArea'].to_numpy() / 1000
y_train = train_rows['SalePrice'].to_numpy()/ 1000

In [115]:
def func(x, w, b):
    return w * x + b

def squared_error(y_hat, y): 
    return (y_hat - y)**2

In [116]:
best_w = None
best_b = None
best_cost = None

learning_rate = 0.01
w, b = 0, 0
for step in range(0,100000):

    if step != 0:
        w = w - learning_rate * dj_dw
        b = b - learning_rate * dj_db

    y_hat = []
    for x in x_train:
        y_hat.append(func(x, w, b))


    sum_of_squared_errors = 0
    dj_dw = 0
    dj_db = 0
    for i in range(len(y_hat)):
        sum_of_squared_errors += squared_error(y_hat[i], y_train[i])
        dj_dw += (y_hat[i] - y_train[i]) * x_train[i]
        dj_db += (y_hat[i] - y_train[i])

    m = len(x_train)
    cost = ( 1/ (2 * m) ) * sum_of_squared_errors
    dj_dw = ( 1/ m ) * dj_dw
    dj_db = ( 1/ m ) * dj_db

    if best_cost is None or cost < best_cost:
        best_cost = cost
        best_w = w
        best_b = b

    if step % 1000 == 0:
        print('step: ', step, w, b, 'cost: ', cost, 'dj_dw', dj_dw, 'dj_db', dj_db)
    if best_cost is not None and (abs(dj_dw) < 1e-6 and abs(dj_db) < 1e-6):
        break

print('Best Parameters are:', step, w, b, cost)

step:  0 0 0 cost:  19409.72205322174 dj_dw -300.45284945034257 dj_db -180.59027739726
step:  1000 101.01960243848234 30.403211612688658 cost:  1463.9404427429147 dj_dw -0.956270662441296 dj_db 1.5521611227373013
step:  2000 107.7609945728989 19.460988667713398 cost:  1446.6697288718426 dj_dw -0.45345973813113677 dj_db 0.7360286202414072
step:  3000 110.95773586380945 14.272230143495154 cost:  1442.7862040035 dj_dw -0.21502880113570597 dj_db 0.34902183921412844
step:  4000 112.47361784741952 11.811741524497373 cost:  1441.9129473729051 dj_dw -0.10196580077526135 dj_db 0.1655047655734273
step:  5000 113.192443044431 10.644987624511382 cost:  1441.7165852614912 dj_dw -0.0483517764728417 dj_db 0.078481700426533
step:  6000 113.53330708889186 10.091717573749207 cost:  1441.6724309116125 dj_dw -0.02292821975894097 dj_db 0.03721570965347821
step:  7000 113.69494346069578 9.829359120030647 cost:  1441.6625022823123 dj_dw -0.010872470458559005 dj_db 0.01764754124183296
step:  8000 113.77159078420937 9.704949786572765 cost:  1441.6602697122485 dj_dw -0.005155682173034626 dj_db 0.008368393745113412
step:  9000 113.80793663963931 9.645955376321856 cost:  1441.6597676923866 dj_dw -0.002444803944974139 dj_db 0.003968258972402818
step:  10000 113.82517169947401 9.617980462027944 cost:  1441.6596548072644 dj_dw -0.001159316290163626 dj_db 0.001881732594206069
step:  11000 113.8333444961793 9.60471486912816 cost:  1441.6596294237083 dj_dw -0.0005497431658212005 dj_db 0.0008923100989231326
step:  12000 113.83722000381462 9.59842437782828 cost:  1441.6596237159129 dj_dw -0.0002606860189325466 dj_db 0.0004231298937531856
step:  13000 113.83905775409448 9.595441451916475 cost:  1441.6596224324478 dj_dw -0.00012361627152531886 dj_db 0.00020064650977552536
step:  14000 113.83992920795511 9.594026960333872 cost:  1441.6596221438438 dj_dw -5.861834343702958e-05 dj_db 9.514577552749578e-05
step:  15000 113.84034244790371 9.593356214061089 cost:  1441.6596220789509 dj_dw -2.7796584948465638e-05 dj_db 4.5117747655096276e-05
step:  16000 113.84053840464094 9.593038148850889 cost:  1441.6596220643576 dj_dw -1.3181029830904726e-05 dj_db 2.1394656185153698e-05
step:  17000 113.84063132654498 9.592887323595495 cost:  1441.6596220610757 dj_dw -6.250391807749749e-06 dj_db 1.0145260743572308e-05
step:  18000 113.84067538974173 9.592815802860228 cost:  1441.659622060339 dj_dw -2.9639108027616403e-06 dj_db 4.8108422745405176e-06
step:  19000 113.84069628433407 9.592781888012453 cost:  1441.6596220601728 dj_dw -1.4054747133485242e-06 dj_db 2.281282220164001e-06
step:  20000 113.84070619246653 9.592765805726797 cost:  1441.6596220601384 dj_dw -6.664704319871284e-07 dj_db 1.0817749819577916e-06
Best Parameters are: 20106 113.84070687196387 9.592764702807488 1441.659622060136

In [117]:
x_valid = validation_rows['GrLivArea'].to_numpy() / 1000
y_valid = validation_rows['SalePrice'].to_numpy() / 1000

sse = 0
valid_y_hat = []
for i in range(len(x_valid)):
    y_hat = func(x_valid[i], best_w, best_b)
    sse += (y_hat - y_valid[i])**2
    valid_y_hat.append(y_hat * 1000)

m = len(x_valid)
cost = ( 1 / (2 * m)) * sse

print('cost: ', cost)

cost:  2117.590975311934

In [118]:
# validation_rows['PredictedSales'] = predictions * 1000
validation_rows['PredictedSales'] = valid_y_hat

C:\Users\alirm\AppData\Local\Temp\ipykernel_14220\3410635853.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  validation_rows['PredictedSales'] = valid_y_hat

In [119]:
test_rows = pd.read_csv('test.csv')[['Id', 'GrLivArea']]
test_rows.head()

     Id  GrLivArea
0  1461        896
1  1462       1329
2  1463       1629
3  1464       1604
4  1465       1280

In [120]:
x_test = test_rows['GrLivArea'].to_numpy() / 1000
predictions = best_w * x_test + best_b

test_rows['SalePrice'] = predictions * 1000
test_rows

        Id  GrLivArea      SalePrice
0     1461        896  111594.038074
1     1462       1329  160887.064141
2     1463       1629  195039.276197
3     1464       1604  192193.258526
4     1465       1280  155308.869505
...    ...        ...            ...
1454  2915       1092  133906.816617
1455  2916       1092  133906.816617
1456  2917       1224  148933.789921
1457  2918        970  120018.250381
1458  2919       2000  237274.178440

[1459 rows x 3 columns]

In [121]:
test_rows[['Id', 'SalePrice']].to_csv('submission.csv', index=False)

In [128]:
# Use the direct formula method
import numpy as np

test_rows = pd.read_csv('test.csv')[['Id', 'GrLivArea']]
x_mean = x_train.mean()
y_mean = y_train.mean()

best_w_dir = np.sum((x_train - x_mean) * (y_train - y_mean)) / np.sum((x_train - x_mean)**2)
best_b_dir = y_mean - best_w_dir * x_mean

predictions = best_w_dir * x_test + best_b_dir
test_rows['SalePrice'] = predictions * 1000

print(best_b_dir, best_w_dir)

9.592751301926938 113.84071512810989

In [129]:
test_rows[['Id', 'SalePrice']].to_csv('submission_dir.csv', index=False)