#### Import Relevant Python Libraries

In [40]:
pip install pandas

Requirement already satisfied: pandas in c:\users\alirm\documents\venvs\ml_venv\lib\site-packages (2.3.3)
Requirement already satisfied: tzdata>=2022.7 in c:\users\alirm\documents\venvs\ml_venv\lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\alirm\documents\venvs\ml_venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\alirm\documents\venvs\ml_venv\lib\site-packages (from pandas) (2026.3.post1)
Requirement already satisfied: numpy>=1.22.4 in c:\users\alirm\documents\venvs\ml_venv\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: six>=1.5 in c:\users\alirm\documents\venvs\ml_venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [41]:
import pandas as pd
import numpy as np

#### Import Data

In [42]:
train_data = pd.read_csv('train.csv')

#### Inspect Data

In [43]:
pd.set_option('display.max_columns', None) 
train_data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,NaN,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

#### Handling Missing Values

Counting missing values per column

In [44]:
missing_values_count = train_data.isna().mean()

print(missing_values_count.sort_values(ascending=False))

PoolQC           0.995205
MiscFeature      0.963014
Alley            0.937671
Fence            0.807534
MasVnrType       0.597260
                   ...
MoSold           0.000000
YrSold           0.000000
SaleType         0.000000
SaleCondition    0.000000
SalePrice        0.000000
Length: 81, dtype: float64

Selecting Only Columns with Zero Missing Values

In [45]:
cleaned_train_data = train_data.loc[:, missing_values_count <= 0]
train_data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,NaN,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [46]:
missing_values_count = cleaned_train_data.isna().mean()

print(missing_values_count.sort_values(ascending=False))

Id               0.0
MSSubClass       0.0
MSZoning         0.0
LotArea          0.0
Street           0.0
                ...
MoSold           0.0
YrSold           0.0
SaleType         0.0
SaleCondition    0.0
SalePrice        0.0
Length: 62, dtype: float64

#### Handling Categorical Data

In [47]:
cleaned_train_data.head()

,Id,MSSubClass,MSZoning,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,ExterQual,ExterCond,Foundation,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,GarageCars,GarageArea,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,8450,Pave,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,Gd,TA,PConc,706,0,150,856,GasA,Ex,Y,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,2,548,Y,0,61,0,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,RL,9600,Pave,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,TA,TA,CBlock,978,0,284,1262,GasA,Ex,Y,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,2,460,Y,298,0,0,0,0,0,0,5,2007,WD,Normal,181500
2,3,60,RL,11250,Pave,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,Gd,TA,PConc,486,0,434,920,GasA,Ex,Y,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,2,608,Y,0,42,0,0,0,0,0,9,2008,WD,Normal,223500
3,4,70,RL,9550,Pave,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,TA,TA,BrkTil,216,0,540,756,GasA,Gd,Y,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,3,642,Y,0,35,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,5,60,RL,14260,Pave,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,Gd,TA,PConc,655,0,490,1145,GasA,Ex,Y,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,3,836,Y,192,84,0,0,0,0,0,12,2008,WD,Normal,250000

In [49]:
cleaned_train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 62 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotArea        1460 non-null   int64
 4   Street         1460 non-null   object
 5   LotShape       1460 non-null   object
 6   LandContour    1460 non-null   object
 7   Utilities      1460 non-null   object
 8   LotConfig      1460 non-null   object
 9   LandSlope      1460 non-null   object
 10  Neighborhood   1460 non-null   object
 11  Condition1     1460 non-null   object
 12  Condition2     1460 non-null   object
 13  BldgType       1460 non-null   object
 14  HouseStyle     1460 non-null   object
 15  OverallQual    1460 non-null   int64
 16  OverallCond    1460 non-null   int64
 17  YearBuilt      1460 non-null   int64
 18  YearRemodAdd   1460 non-null   int64
 19  RoofStyle      1460 non-null   object
 20  RoofMatl       1460 non-null   object
 21  Exterior1st    1460 non-null   object
 22  Exterior2nd    1460 non-null   object
 23  ExterQual      1460 non-null   object
 24  ExterCond      1460 non-null   object
 25  Foundation     1460 non-null   object
 26  BsmtFinSF1     1460 non-null   int64
 27  BsmtFinSF2     1460 non-null   int64
 28  BsmtUnfSF      1460 non-null   int64
 29  TotalBsmtSF    1460 non-null   int64
 30  Heating        1460 non-null   object
 31  HeatingQC      1460 non-null   object
 32  CentralAir     1460 non-null   object
 33  1stFlrSF       1460 non-null   int64
 34  2ndFlrSF       1460 non-null   int64
 35  LowQualFinSF   1460 non-null   int64
 36  GrLivArea      1460 non-null   int64
 37  BsmtFullBath   1460 non-null   int64
 38  BsmtHalfBath   1460 non-null   int64
 39  FullBath       1460 non-null   int64
 40  HalfBath       1460 non-null   int64
 41  BedroomAbvGr   1460 non-null   int64
 42  KitchenAbvGr   1460 non-null   int64
 43  KitchenQual    1460 non-null   object
 44  TotRmsAbvGrd   1460 non-null   int64
 45  Functional     1460 non-null   object
 46  Fireplaces     1460 non-null   int64
 47  GarageCars     1460 non-null   int64
 48  GarageArea     1460 non-null   int64
 49  PavedDrive     1460 non-null   object
 50  WoodDeckSF     1460 non-null   int64
 51  OpenPorchSF    1460 non-null   int64
 52  EnclosedPorch  1460 non-null   int64
 53  3SsnPorch      1460 non-null   int64
 54  ScreenPorch    1460 non-null   int64
 55  PoolArea       1460 non-null   int64
 56  MiscVal        1460 non-null   int64
 57  MoSold         1460 non-null   int64
 58  YrSold         1460 non-null   int64
 59  SaleType       1460 non-null   object
 60  SaleCondition  1460 non-null   object
 61  SalePrice      1460 non-null   int64
dtypes: int64(35), object(27)
memory usage: 707.3+ KB

#### Clean Data

In [50]:
cat_cols = cleaned_train_data.select_dtypes('object').columns
cat_cols

Index(['MSZoning', 'Street', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
       'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'ExterQual', 'ExterCond', 'Foundation', 'Heating',
       'HeatingQC', 'CentralAir', 'KitchenQual', 'Functional', 'PavedDrive',
       'SaleType', 'SaleCondition'],
      dtype='object')

In [52]:
cleaned_train_data[cat_cols]

,MSZoning,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,ExterQual,ExterCond,Foundation,Heating,HeatingQC,CentralAir,KitchenQual,Functional,PavedDrive,SaleType,SaleCondition
0,RL,Pave,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,Gd,TA,PConc,GasA,Ex,Y,Gd,Typ,Y,WD,Normal
1,RL,Pave,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,Gable,CompShg,MetalSd,MetalSd,TA,TA,CBlock,GasA,Ex,Y,TA,Typ,Y,WD,Normal
2,RL,Pave,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,Gd,TA,PConc,GasA,Ex,Y,Gd,Typ,Y,WD,Normal
3,RL,Pave,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,Gable,CompShg,Wd Sdng,Wd Shng,TA,TA,BrkTil,GasA,Gd,Y,Gd,Typ,Y,WD,Abnorml
4,RL,Pave,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,Gd,TA,PConc,GasA,Ex,Y,Gd,Typ,Y,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,RL,Pave,Reg,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,TA,TA,PConc,GasA,Ex,Y,TA,Typ,Y,WD,Normal
1456,RL,Pave,Reg,Lvl,AllPub,Inside,Gtl,NWAmes,Norm,Norm,1Fam,1Story,Gable,CompShg,Plywood,Plywood,TA,TA,CBlock,GasA,TA,Y,TA,Min1,Y,WD,Normal
1457,RL,Pave,Reg,Lvl,AllPub,Inside,Gtl,Crawfor,Norm,Norm,1Fam,2Story,Gable,CompShg,CemntBd,CmentBd,Ex,Gd,Stone,GasA,Ex,Y,Gd,Typ,Y,WD,Normal
1458,RL,Pave,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,1Fam,1Story,Hip,CompShg,MetalSd,MetalSd,TA,TA,CBlock,GasA,Gd,Y,Gd,Typ,Y,WD,Normal
1459,RL,Pave,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,Norm,1Fam,1Story,Gable,CompShg,HdBoard,HdBoard,Gd,TA,CBlock,GasA,Gd,Y,TA,Typ,Y,WD,Normal

In [59]:
cleaned_train_data['LandSlope'].unique()

array(['Gtl', 'Mod', 'Sev'], dtype=object)

In [ ]:
nominal_cat_cols = [
    'Street',
    'Utilities',
    'CentralAir',

]


nominal_cat_cols = [
    'LandSlope',
    

]

In [56]:
print(cleaned_train_data[cat_cols].nunique().sort_values())

Street            2
Utilities         2
CentralAir        2
LandSlope         3
PavedDrive        3
KitchenQual       4
LandContour       4
LotShape          4
ExterQual         4
MSZoning          5
ExterCond         5
HeatingQC         5
LotConfig         5
BldgType          5
RoofStyle         6
Heating           6
SaleCondition     6
Foundation        6
Functional        7
RoofMatl          8
Condition2        8
HouseStyle        8
SaleType          9
Condition1        9
Exterior1st      15
Exterior2nd      16
Neighborhood     25
dtype: int64

In [ ]:

# Leveraging Gradient Descent to find the best model parameters
m = len(X_train)
dj_dw_1, dj_dw_2, dj_dw_3, dj_dw_4, dj_db = 0, 0, 0, 0, 0
w_1, w_2, w_3, w_4, b = 0, 0, 0, 0, 0
learning_rate = 0.01
for iter in range(10000):

    w_1 = w_1 - learning_rate * dj_dw_1
    w_2 = w_2 - learning_rate * dj_dw_2
    w_3 = w_3 - learning_rate * dj_dw_3
    w_4 = w_4 - learning_rate * dj_dw_4
    b = b - learning_rate * dj_db

    error_sqrd = 0
    dj_dw_val_1, dj_dw_val_2, dj_dw_val_3, dj_dw_val_4, dj_db_val = 0, 0, 0, 0, 0
    for i in range(m):
        y_hat = w_1 * X_train[i, 0] + w_2 * X_train[i, 1] + w_3 * X_train[i, 2] + w_4 * X_train[i, 3] + b

        error_sqrd += (y_hat - y_train[i])**2

        dj_dw_val_1 += (y_hat - y_train[i]) * X_train[i, 0]
        dj_dw_val_2 += (y_hat - y_train[i]) * X_train[i, 1]
        dj_dw_val_3 += (y_hat - y_train[i]) * X_train[i, 2]
        dj_dw_val_4 += (y_hat - y_train[i]) * X_train[i, 3]

        dj_db_val += (y_hat - y_train[i])


    cost = error_sqrd / (2 * m)
    dj_dw_1 = dj_dw_val_1 / m
    dj_dw_2 = dj_dw_val_2 / m
    dj_dw_3 = dj_dw_val_3 / m
    dj_dw_4 = dj_dw_val_4 / m
    dj_db = dj_db_val / m

    print(iter, w_1, w_2, w_3, w_4, b, cost) 

predictions = []
for i in range(m):
    predictions.append((w_1 * X_train[i, 0] + w_2 * X_train[i, 1] + w_3 * X_train[i, 2] + w_4 * X_train[i, 3] + b ))

print(predictions)

0 0.0 0.0 0.0 0.0 0.0 1.9519633853882916
1 0.03037411098753427 0.2111784888286987 3.5770419863013644e-05 1.3480404452054807e-05 0.01809211958904106 2.2069876189204
2 0.023122952548637967 -0.028620625231145336 2.866760673794687e-05 9.22076787762958e-06 0.013333730024965074 2.5338577293576336
3 0.05765636253335965 0.23730079615742272 6.91901773323941e-05 2.4713049889296875e-05 0.03395207375032188 2.95086958257125
4 0.0449394065859674 -0.06378967068972241 5.5870183086750085e-05 1.792018952965375e-05 0.02587439321399749 3.4810319412686597
5 0.08481173212868434 0.27094656593731326 0.00010248889177677479 3.597982868959742e-05 0.04973537738119464 4.153278831175516
6 0.06533056947332597 -0.10721661075382766 8.14716494109412e-05 2.6039278539625832e-05 0.037549865617938175 5.003993831377833
7 0.11202160516105117 0.3140271301614909 0.00013587258938543763 4.73635238828745e-05 0.06555221051552727 6.078926540858717
8 0.08414050599958073 -0.16104998742679322 0.00010529361799941265 3.35015999564041e-05 0.0482654651366689 7.4356021206020895
9 0.1395075549890603 0.36894630686244423 0.00016959311700673652 5.8965979242161224e-05 0.08153715948810578 9.146350770141943
10 0.10116678158282508 -0.2279903967943573 0.0001271047290348302 4.020884994151892e-05 0.05789826896285216 11.302116635834937
11 0.16754187879071603 0.4387270851601722 0.00020396014860275412 7.09130710280804e-05 0.09785561559449098 14.017246683773045
12 0.11614869210840234 -0.3114325440767064 0.0001466072362142593 4.6035296058615254e-05 0.06628996533927042 17.43551166358814
13 0.19646083814240803 0.5271709046556484 0.00023935627414493373 8.336095681636837e-05 0.11471181638919237 21.737676156729865
14 0.12875245967320517 -0.415643846096455 0.0001634201346110132 5.082078513284406e-05 0.07323786264756454 27.151016259255634
15 0.22668130038465975 0.6390579150583654 0.00027625596420420616 9.650393003996755e-05 0.1323589523514895 33.9612859885798
16 0.1385526137985571 -0.5459889841424211 0.000177057941358368 5.436195020424514e-05 0.07848358185241017 42.52776242447244
17 0.2587216559074339 0.7803987594682443 0.0003152494075722458 0.00011058429342601276 0.15111187040519225 53.3021616843537
18 0.14500857687672458 -0.7092122294175444 0.0001869040108990212 5.640115329540158e-05 0.08169883637683431 66.8524216253111
19 0.29322811163761875 0.9587511373555414 0.00035707247584049466 0.00012590477080969998 0.1713630425167914 83.89260338957504
20 0.14743522015769717 -0.9137924048843394 0.00019217697883224192 5.6612581518734255e-05 0.08246755016115304 105.32048605617416
21 0.3310077440881276 1.1836178138126279 0.0004026443914695333 0.00014284411045815303 0.19360263951486203 132.26483368955618
22 0.14496583917181718 -1.1703891714991959 0.00019188856665600934 5.458476418733242e-05 0.08026337188769675 166.14482331009575
23 0.37307005123532366 1.4669470296466844 0.0004531150814879192 0.00016187670107450423 0.2184437664234371 208.74476256183254
24 0.13650559840907528 -1.492404134893345 0.00018479052489952602 4.979859017529088e-05 0.0744214009871225 262.3080308276436
25 0.42067918996711257 1.823761658097586 0.0005099247089212153 0.0001835972329223204 0.24665418736331096 329.65518962158797
26 0.12067299332690601 -1.8966863136496106 0.00016930792032775183 4.159966787925973e-05 0.0641026363195481 414.33248055677353
27 0.47541964844690465 2.2729502322385655 0.0005748785152171838 0.0002087517021362339 0.279196209755573 520.7985290378002
28 0.09572624691886711 -2.4044191107030692 0.00014345525396917833 2.91635722902859e-05 0.048249275301893935 654.6590832888453
29 0.5392788100886288 2.8382614893117064 0.0006502409130582179 0.00023827639025088865 0.31727682714999783 822.9621473017377
30 0.05947076493429798 -3.04223548520682 0.0001047309928205772 1.1452149213168878e-05 0.02552850956104713 1034.5690459186205
31 0.6147507551760036 3.5495547930449614 0.0007388537824781325 0.00027334687086983615 0.3624107601143057 1300.620957952957
32 0.00914277663630314 -3.843620036547391 4.998496162936467e-05 -1.2841424145788242e-05 -0.005738142429390913 1635.1254794714716
33 0.7049667643072633 4.444372266506205 0.0008442851974877045 0.0003154396233152082 0.4164997136947633 2055.694098729841
34 -0.05873696577865484 -4.850671817600997 -2.4748387686685707e-05 -4.536171495023861e-05 -0.04766368670794374 2584.4694094797837
35 0.8138593936729231 5.569915405522458 0.0009710164125508261 0.00036640949684187477 0.4819320237460609 3249.2908787458964
36 -0.14854713230985672 -6.116320686064258 -0.00012445960787700974 -8.817788383757311e-05 -0.10290736749887341 4085.160544630526
37 0.9463687596933935 6.985530237858109 0.0011246769525903786 0.000428587103511214 0.5617079378794765 5136.085810477363
38 -0.26579708993500273 -7.70711388065261 -0.0002554278269959764 -0.00014389288005403421 -0.17481512516539333 6457.396355161985
39 1.108701892811847 8.76583186735525 0.0013123401827914458 0.0005049012670351491 0.6595971264080642 8118.657140632975
40 -0.4174176839496604 -9.706719530266799 -0.00042555213513920695 -0.00021578073179057404 -0.26759619372807986 10207.330881264355
41 1.3086588142540883 11.004632904693246 0.0015428949186449832 0.0005990329740599214 0.7803367155316515 12833.38279738579
42 -0.6121268356574128 -12.220331549448815 -0.0006447682349474285 -0.0003079591600427304 -0.3865451359034763 16135.07008490786
43 1.5560425024314253 13.819882609595926 0.0018275126400791517 0.0007156089329126507 0.9298802684396154 20286.22090611261
44 -0.8608892051292172 -15.38020782980578 -0.0009255722925070196 -0.00042560660403021 -0.5383210058084499 25505.38612726759
45 1.8631743323204797 17.359876781434682 0.0021802349069298755 0.0008604449301018423 1.1157108223373404 32067.345625439542
46 -1.177494120085435 -19.35263330305636 -0.0012836795691598783 -0.0005752350843928535 -0.7312983371313981 40317.57495068608
47 2.2455421241342854 21.811065337771755 0.00261871190140666 0.0010408517966311991 1.3472344618422545 50690.43398713412
48 -1.5792821984313608 -24.34667446826325 -0.0017388525106843225 -0.0007650332701305848 -0.9760084360402375 63732.035212948664
49 2.722614919257046 27.407868635754728 0.003165130979792647 0.0012660200924857095 1.636275149300915 80128.99553158483
50 -2.088058920409003 -30.62518629315598 -0.002315941891910677 -0.0010052978113480905 -1.2856942124658115 100744.58540605502
51 3.3188673793212637 34.4450193479407 0.0038473841192805734 0.0015475037620245535 1.9976968635830294 126664.17848255081
52 -2.7312432488680014 -38.51865098285805 -0.0030461958317969918 -0.0013089756468931798 -1.6770077609781011 159252.39454361072
53 4.065067740601991 43.29307966998054 0.004700535723260953 0.0018998282236599529 2.4501858014794915 200224.94426364393
54 -3.5433117709974695 -48.44257720201597 -0.0039689055968644 -0.0016923458385984292 -2.1708874179684536 251738.95826279928
55 4.999897131629751 54.417950813053466 0.005768668061726181 0.002341254908446635 3.0172338228478357 316506.5561199821
56 -4.567614393511747 -60.91937578773988 -0.0051334748421679715 -0.0021758768296520122 -2.793660470942506 397937.6345474288
57 6.171985507613131 68.40540192049104 0.007107201505277001 0.0028947424989639982 3.7283749157772585 500319.3922651562
58 -5.858657184882128 -76.60586366988255 -0.0066020212321789545 -0.0027853042603802423 -3.5784295758926032 629042.0432341733
59 7.642471389396258 85.99190981159413 0.008785811708256201 0.0035891554757913353 4.620739779099358 790882.6016405355
60 -7.484972552634021 -96.32784403009623 -0.008452647412772102 -0.0035529860866660686 -4.566815875423998 994361.6793947651
61 9.488220172052882 108.10343320925881 0.010892097324842354 0.004460783599179205 5.741010367882936 1250192.0808875186
62 -9.53272786583904 -121.12358328223232 -0.010783553545615634 -0.004519606345702963 -5.811150589947175 1571842.8127012781
63 11.80587044072825 135.90416284418606 0.013536191356150931 0.005555252323698321 7.147877304884581 1976248.2023660494
64 -12.110262510716046 -152.29847385814887 -0.013718207922978114 -0.005736317269427881 -7.377230465532422 2484699.4599747076
65 14.716921324434812 170.8578140402516 0.016856558906865715 0.006929924725564303 8.915129535916039 3123965.6217592075
66 -15.353792247557775 -191.49376069536189 -0.01741184788696285 -0.0072674325241818315 -9.34778214804363 3927702.891272949
67 18.37412872728318 214.80468872449896 0.021027286592252663 0.008656921399593502 11.13553889359474 4938226.577434783
68 -19.43458119348407 -240.77294975134177 -0.02205965331528116 -0.00919381337093753 -11.826817876842652 6208738.9187579835
69 22.96954718666177 270.0585640367732 0.026267247369103408 0.010826917317727204 13.925744084434099 7806130.084666495
70 -24.56795902334263 -302.73044779589156 -0.027907022993250465 -0.011617126021438842 -14.945111817703138 9814499.821535217
71 28.74464074717072 339.5285085485499 0.03285162330184474 0.013553915546686349 17.432391232065342 12339585.151728392
72 -31.024658128452792 -380.6281531694756 -0.03526249490483381 -0.014665194332476175 -18.867085354188134 15514327.23595544
73 36.00299516904746 426.8720394938723 0.041126392916066026 0.01698124915217977 21.83985426479034 19505870.48414501
74 -39.14506761445029 -478.56718876304376 -0.044513990673065995 -0.018498729648084276 -23.79946383584295 24524362.405325312
75 45.12630074537983 536.687684462707 0.05152654587188521 0.0212891272788916 27.37994161161012 30834017.49263801
76 -49.357154585751594 -601.7038186490161 -0.05614923939061944 -0.02331979210377867 -30.00216054552952 38767027.63695587
77 56.59444719403022 674.7570855805552 0.064598983926207 0.026704122693526 34.34410024641859 48741051.4271352
78 -62.19899624014834 -756.5209159822721 -0.07078145611857467 -0.02938242886528612 -37.801960907280716 61281203.11683059
79 71.01078858348063 848.3493925199991 0.08103131387755405 0.03351110029270188 43.09875960090494 77047698.93707131
80 -78.34710904779237 -951.1692744633788 -0.08918162698017076 -0.03700604938585869 -47.6097273836061 96870616.28278643
81 89.13390844471749 1066.603970084041 0.10168804838934728 0.042068214589861735 54.10462317511043 121793595.78137647
82 -98.6520664948278 -1195.8967327933274 -0.11231910060155742 -0.046592241865332854 -59.94203086910966 153128787.07794553
83 111.91755744430031 1341.0115692209715 0.1276561205988929 0.05282576577154198 67.94092351370452 192525931.13305923
84 -124.1832806015772 -1503.587704743446 -0.14141262296563453 -0.05864591626710598 -75.44834743424715 242059216.09069252
85 140.5608662642621 1686.0192942516505 0.1603021087732461 0.06634990706002487 85.33591752825379 304336479.5201401
86 -156.28530488131977 -1890.4415201197348 -0.1779945025718195 -0.07380188703463124 -94.94525227865401 382636506.33183444
87 176.57147730552916 2119.791216735991 0.20134418378587374 0.08335245153188377 107.2052276886547 481081650.85314757
88 -196.648622988592 -2376.8252900423367 -0.22399128408134003 -0.09285829503933203 -119.45941114383058 604854871.3032317
89 221.84491898414038 2665.1646809184876 0.25294256731783493 0.1047283476672108 134.70004767769015 760472603.1382086
90 -247.39864995123432 -2988.34619834942 -0.28182517776944216 -0.11681862836495817 -150.2816326052567 956127837.5530885
91 278.76440153259773 3350.8526484992126 0.31781326324325276 0.1316027966490773 169.26775044873196 1202121467.6011102
92 -311.2076317398537 -3757.1996733221913 -0.35454158486147347 -0.1469445542465378 -189.0348269992236 1511404611.5207982
93 350.32628837390905 4212.955384000799 0.39937104994982087 0.16539049205344575 212.7280895906854 1900260465.6099727
94 -391.4353344842972 -4723.864418525789 -0.44596943273073797 -0.18482234366975359 -237.75944989874935 2389161584.9631004
95 440.29784890815915 5296.861068222757 0.5019092618801879 0.2078701007915918 267.3690058635499 3003847726.3472357
96 -492.3059303693742 -5939.233543064027 -0.5609227613156236 -0.2324463857654579 -299.0209285827128 3776680999.6880045
97 553.4155981092906 6659.635403632694 0.6308258254658312 0.2612779065914091 336.0670829446915 4748349674.432548
98 -619.1303929315304 -7467.293991388578 -0.7054541739154334 -0.2923241888807558 -376.04472730703833 5970010343.102346
99 695.6346651516437 8373.026020082163 0.7929074498348234 0.3284255461768581 422.43899416209047 7505981223.059845
100 -778.5861104656262 -9388.49533978011 -0.8871734960896991 -0.36760839644261295 -472.8861623195744 9437128393.940369
101 874.4423198716647 10527.239857356433 0.9966869344183018 0.41284803674166753 531.031913610092 11865123250.00335
102 -979.0684386805219 -11803.985320522914 -1.1156484194740877 -0.46226276800975313 -594.6439070711817 14917795314.546225
103 1099.2521636638317 13235.692396894096 1.2528924050524082 0.5189898880950745 667.5629164472318 18755862232.344746
104 -1231.1327012130278 -14840.935066434691 -1.4029082236830162 -0.5812708641140703 -747.7284282850978 23581391262.010307
105 1381.899738245876 16640.978781110432 1.5750121300410345 0.6524390979462757 839.21997236723 29648437750.480164
106 -1548.049908525743 -18659.234440213186 -1.7640770963435832 -0.7308984217699781 -940.1994855567782 37276420686.0233
107 1737.2656451951207 20922.38118891894 1.9800046527197184 0.8202213497545578 1055.0403790030293 46866939528.34854
108 -1946.5054527801894 -23459.90994553973 -2.218170394411332 -0.9190232342460956 -1182.190463225745 58924917691.41188
109 2184.0589823687533 26305.307717152165 2.489191627711599 1.0311699021280982 1326.386559095806 74085185844.91873
110 -2447.4775637031526 -29495.70840768487 -2.7890957684817614 -1.1555499026708311 -1486.4418748227552 93145904597.11194
111 2745.8023437134852 33073.15970785832 3.129380367083602 1.2963906437768742 1667.5442712863398 117110586202.4391
112 -3077.341774553267 -37084.40363519292 -3.506911857475961 -1.4529312953913327 -1868.9721281332893 147240927660.7695
113 3452.0702409170217 41582.25231472345 3.9342751964208054 1.6298467983190026 2096.474729241212 185123236774.93484
114 -3869.2595463176276 -46625.526634239905 -4.4094108216921954 -1.826824168974916 -2349.9208654412787 232751948378.0135
115 4340.046147553907 52280.57384936319 4.946251926155111 2.0490940625875673 2635.7602268209157 292634627708.1662
116 -4864.924158681944 -58621.40019108695 -5.544108031716237 -2.296913468108901 -2954.609279286119 367923989168.159
117 5456.480141274273 65731.37155302946 6.218588860843323 2.5762048821355856 3313.7930547389105 462583881017.7042
118 -6116.7557857669635 -73703.58525523072 -6.970743666702668 -2.8879487022932127 -3714.8732274342983 581597974791.4886
119 6860.150210343998 82642.80554180962 7.81827180498446 3.238930525367195 4166.270303016216 731232146562.0162
120 -7690.661323384735 -92666.13147733067 -8.764427926636042 -3.6310469626777158 -4670.739333149386 919364363944.6951
121 8624.956807859586 103905.23215172521 9.82952074384244 4.072162137389476 5238.07324786792 1155899446797.3228
122 -9669.504267712548 -116507.38248240022 -11.019595448291543 -4.565331180516514 -5872.532314398679 1453290538012.103
123 10843.813576300998 130638.0795841919 12.358223872619892 5.1197676954186075 6585.630269331168 1827194738891.3901
124 -12157.467328199882 -146482.5368500314 -13.854977117718743 -5.7399898785740895 -7383.5244890547965 2297297427119.577
125 13633.539082010278 164248.78376951994 15.537512417572302 6.436901578109328 8279.887702959499 2888348656176.7837
126 -15285.537458362758 -184169.73204188806 -17.419851036155663 -7.216866857657399 -9283.266947734344 3631466200742.864
127 17141.007100538576 206506.88731470628 19.53476975327773 8.092908343441406 10410.045035533822 4565773851067.467
128 -19218.402081381704 -231553.13047532615 -21.90190174138302 -9.07371716056994 -11671.777774477498 5740461209532.072
129 21550.87925422597 259637.202710681 24.56044383336807 10.174973593800042 13088.251096067019 7217373433955.513
130 -24163.119584269487 -291127.3820741667 -27.537101458265468 -11.408300734083086 -14674.807817488876 9074267272927.465
131 27095.32711135008 326436.9446727965 30.87912689320907 12.792714139672045 16455.508488036507 11408904817523.535
132 -30380.020566392137 -366028.963060327 -34.622133608385006 -14.34352931279676 -18450.46124321272 14344200498000.45
133 34066.25559771996 410422.9984197519 38.823485750766515 16.08394912574554 20689.09712048653 18034692305505.1
134 -38196.413773296714 -460201.30573539354 -43.53001265401324 -18.03393749898902 -23197.519433902442 22674677936883.688
135 42830.671261157324 516017.07729856845 48.811776110723095 20.221955958730597 26011.907673441663 28508444215843.71
136 -48023.81830838914 -578602.4130354797 -54.72972263285316 -22.673818729061026 -29165.906466784338 35843128350936.76
137 53850.00450010246 648778.5179686471 61.36986296817931 25.424593048336078 32704.17638765268 45064888152252.32
138 -60379.629367142836 -727465.8883889274 -68.81090831677867 -28.507454470452174 -36669.8471633056 56659232539393.016
139 67704.40303661552 815696.969388839 77.15890644622706 31.965769657156343 41118.23899405428 71236582705077.42
140 -75914.3581554197 -914629.1236251987 -86.51491893926607 -35.84197519767753 -46104.410455880905 89564409683261.12
141 85123.27564104513 1025560.3851516236 97.01017067651028 40.18986672625445 51697.080550551764 112607640306407.22
142 -95445.88012418427 -1149945.9234328377 -108.77383888744137 -45.06353025453899 -57966.30905037782 141579458852248.0
143 107023.69418004263 1289417.6932930364 121.96878834716617 50.52986790673887 64997.65780138355 178005178994547.28
144 -120002.49462801625 -1445805.290295476 -136.75956025385344 -56.65761791641671 -72880.05044882768 223802548800162.94
145 134558.6757860703 1621160.5023042466 153.34878504218833 63.530155363248184 81720.2219389565 281382716684797.16
146 -150877.06302030146 -1817783.682991269 -171.94548082876858 -71.2346459935228 -91630.81613625376 353777174001775.8
147 169177.88711699506 2038254.4691106733 192.80226030381104 79.87517050702326 102745.18555835288 444797357560820.25
148 -189695.0754575787 -2285465.088882327 -216.18407582032953 -89.56206869450239 -115205.79996113823 559235314859788.44
149 212703.96667491418 2562658.834215761 242.4063676753432 100.42544859417058 129179.47478277437 703115996689708.1
150 -238500.23000678327 -2873472.085311909 -271.80442731289236 -112.60479169793157 -144846.1821002514 884014459860983.6
151 267428.48341576743 3221982.5358659085 304.7726730658378 126.26292434530657 162414.80691520017 1111454680198646.5
152 -299862.0296400734 -3612762.173621095 -341.73484621251805 -141.57597268540846 -182112.4749427742 1397410972587186.5
153 336232.58369643067 4050937.770549584 383.1846489560885 158.74789384526397 204200.9618288857 1756938416920471.2
154 -377011.06190377555 -4542257.635418359 -429.6570425025591 -178.00089189211647 -228966.68123593277 2208965480739013.0
155 422738.67840210756 5093167.527153203 481.77054326636016 199.59063166349924 256737.90470243598 2777290568698045.5
156 -474009.08349056134 -5710894.720077366 -540.1999605935358 -223.79725534345428 -287875.58996943885 3491834965387767.5
157 531501.1563060329 6403543.311130814 605.7207241180746 250.94143370664247 322791.6101942962 4390218136671416.0
158 -595962.8643589068 -7180200.049466148 -679.183484846741 -281.376158597422 -361940.6483396003 5519738326298134.0
159 668246.1643738296 8051054.029695759 761.5609432967825 315.50382639599513 405839.68598927883 6939862722608215.0
160 -749293.0499047093 -9027529.88294124 -853.9248459251395 -353.7690265505729 -455061.24731634697 8725358298089353.0
161 840173.079010364 10122438.132597039 957.4959052418116 396.67690242770357 510254.46253257804 1.0970228154804828e+16
162 -942072.1962904885 -11350142.784031032 -1073.62385970993 -444.7872124579958 -572140.0175019647 1.3792660617137648e+16
163 1056333.5401632735 12726750.234101811 1203.8412298464855 498.7342768351306 641533.1882935492 1.7341251632603184e+16
164 -1184449.7758788597 -14270320.107318645 -1349.8472809126974 -559.2226587660845 -719340.9437359904 2.180282807884166e+16
165 1328108.003740849 16001102.640544524 1513.5665511265279 627.0490850653674 806587.4499221644 2.7412283859707012e+16

C:\Users\alirm\AppData\Local\Temp\ipykernel_55216\4284080532.py:19: RuntimeWarning: overflow encountered in scalar add
  error_sqrd += (y_hat - y_train[i])**2
C:\Users\alirm\AppData\Local\Temp\ipykernel_55216\4284080532.py:19: RuntimeWarning: overflow encountered in scalar power
  error_sqrd += (y_hat - y_train[i])**2

3073 4.988021806823697e+150 6.009593812508654e+151 5.684554100342486e+147 2.3550301497858427e+147 3.0293289836205013e+150 inf
3074 -5.5929963837402216e+150 -6.738470231851608e+151 -6.374007924924596e+147 -2.6406610920049152e+147 -3.396742577863328e+150 inf
3075 6.271345587490603e+150 7.555748771412476e+151 7.14708248172948e+147 2.9609349177387612e+147 3.808718103135809e+150 inf
3076 -7.03196869428993e+150 -8.472151324027457e+151 -8.013919750695782e+147 -3.320053305450276e+147 -4.2706602742559775e+150 inf
3077 7.884844333265341e+150 9.499700192361266e+151 8.985891786581313e+147 3.7227275361557225e+147 4.7886293194268255e+150 inf
3078 -8.84116139628302e+150 -1.0651875809726255e+152 -1.007574990916764e+148 -4.174240300811337e+147 -5.369420484486939e+150 inf
3079 9.913465825235062e+150 1.1943793590145827e+152 1.129779198806867e+148 4.680515004036577e+147 6.020653179870315e+150 inf
3080 -1.1115825202492236e+151 -1.339240222776074e+152 -1.2668050016757056e+148 -5.248193473373866e+147 -6.750870939798795e+150 inf
3081 1.2464013303786401e+151 1.501670604707269e+152 1.4204500436592783e+148 5.884723093550421e+147 7.569653505070533e+150 inf
3082 -1.3975717034677044e+151 -1.683801432104194e+152 -1.5927299970103714e+148 -6.598454508862479e+147 -8.487742499863978e+150 inf
3083 1.5670768465405014e+151 1.888022082784812e+152 1.7859050057413604e+148 7.398751175436901e+147 9.517182351311075e+150 inf
3084 -1.7571405008201433e+151 -2.1170117313824105e+152 -2.002509336496981e+148 -8.296112200592698e+147 -1.0671478300567942e+151 inf
3085 1.9702561150326244e+151 2.3737744974890437e+152 2.2453846256469216e+148 9.302310080830264e+147 1.1965773578332696e+151 inf
3086 -2.209219557008416e+151 -2.6616788567580937e+152 -2.517717158767993e+148 -1.0430545145439942e+148 -1.3417048069179304e+151 inf
3087 2.4771657927262677e+151 2.984501832000898e+152 2.8230796715857125e+148 1.1695618731874306e+148 1.5044341070989395e+151 inf
3088 -2.7776100139917595e+151 -3.346478544021525e+152 -3.16547822076256e+148 -1.3114127364778166e+148 -1.6869001071865613e+151 inf
3089 3.1144937543064086e+151 3.752357772247824e+152 3.5494047394326744e+148 1.4704680486114217e+148 1.891496582135691e+151 inf
3090 -3.4922365979208627e+151 -4.207464254059803e+152 -3.9798959669581536e+148 -1.6488144592788634e+148 -2.120907637025469e+151 inf
3091 3.915794160445831e+151 4.717768540121447e+152 4.4625995260101125e+148 1.8487916984624265e+148 2.3781429198851062e+151 inf
3092 -4.390723101667948e+151 -5.289965322149428e+152 -5.00384801383786e+148 -2.0730232713986044e+148 -2.66657710532437e+151 inf
3093 4.923254023476527e+151 5.931561260702085e+152 5.610742079734973e+148 2.324450876393583e+148 2.9899941669542844e+151 inf
3094 -5.520373209248793e+151 -6.650973465203362e+152 -6.291243578591821e+148 -2.6063729970197546e+148 -3.352637019409573e+151 inf
3095 6.189914277035997e+151 7.457639918162696e+152 7.054280022624897e+148 2.922488174985004e+148 3.759263181227352e+151 inf
3096 -6.940660948948372e+151 -8.362143292248582e+152 -7.909861701578062e+148 -3.2769435313722384e+148 -4.2152071888235926e+151 inf
3097 7.782462284974338e+151 9.37634978457437e+152 8.869213007908445e+148 3.674389172800508e+148 4.726450580379224e+151 inf
3098 -8.7263618929873e+151 -1.0513564789565715e+153 -9.94491968980401e+148 -4.120039196262811e+148 -5.299700367753816e+151 inf
3099 9.784742810049086e+151 1.178870745268528e+153 1.1151093963857485e+149 4.619740092964727e+148 5.942477025903188e+151 inf
3100 -1.0971489955710704e+152 -1.3218506394988234e+153 -1.250355965350448e+149 -5.180047448554491e+148 -6.663213154134087e+151 inf
3101 1.2302172288538478e+152 1.4821719176222658e+153 1.402005978206873e+149 5.808311945976977e+148 7.471364103537004e+151 inf
3102 -1.379424705557941e+152 -1.661937837561585e+153 -1.5720489343823474e+149 -6.512775799224254e+148 -8.377532021917466e+151 inf
3103 1.5467288814321377e+152 1.863506751868429e+153 1.7627156306804661e+149 7.302680883098932e+148 9.393604943577762e+151 inf
3104 -1.7343246231686205e+152 -2.0895230469957623e+153 -1.9765074271469618e+149 -8.188389977546912e+148 -1.053291274866524e+152 inf
3105 1.9446730029014477e+152 2.3429518350544297e+153 2.2162290624603616e+149 9.181522717166726e+148 1.181040203812784e+152 inf
3106 -2.1805335850588397e+152 -2.627117853175815e+153 -2.4850254493521996e+149 -1.0295108029417762e+149 -1.3242832218455922e+152 inf
3107 2.445000629142018e+152 2.9457490808020768e+153 2.7864229327777753e+149 1.1543755061370628e+149 1.4848995368660482e+152 inf
3108 -2.7415436833749168e+152 -3.3030256471198973e+153 -3.124375552103045e+149 -1.2943844837386926e+149 -1.664996277391537e+152 inf
3109 3.0740531017737844e+152 3.703634670255496e+153 3.503316914222986e+149 1.4513745162092507e+149 1.8669361360153554e+152 inf
3110 -3.446891081776257e+152 -4.1528317476672e+153 -3.928218358135513e+149 -1.6274051587958335e+149 -2.093368365616066e+152 inf
3111 3.8649488919931407e+152 4.656509904429355e+153 4.404654174032996e+149 1.8247857608748684e+149 2.3472635349568108e+152 inf
3112 -4.333711040855211e+152 -5.2212769039412106e+153 -4.938874732522525e+149 -2.0461057623508767e+149 -2.631952499634052e+152 inf
3113 4.8593272279843005e+152 5.854541935301832e+153 5.537888483357279e+149 2.2942686645681647e+149 2.9511700996357218e+152 inf
3114 -5.448693022221054e+152 -6.564612814603875e+153 -6.209553899423968e+149 -2.5725301214008477e+149 -3.3091041567790687e+152 inf
3115 6.109540324724054e+152 7.360804975332315e+153 6.9626825721985925e+149 2.8845406502382128e+149 3.710450414824911e+152 inf
3116 -6.850538803930445e+152 -8.253563677714985e+153 -7.807154811184672e+149 -3.2343935231925776e+149 -4.1604741430306947e+152 inf
3117 7.681409633101169e+152 9.254601040291878e+153 8.754049263882632e+149 3.626678466814512e+149 4.665079211318177e+152 inf
3118 -8.613053022580866e+152 -1.0377049691422906e+154 -9.81578825677929e+149 -4.066541874803563e+149 -5.230885543256895e+152 inf
3119 9.657691219865144e+152 1.163563505649123e+154 1.1006300764086872e+150 4.5597543236459035e+149 5.8653159629677985e+152 inf
3120 -1.0829028853500841e+153 -1.3046868541041255e+154 -1.234120514222338e+150 -5.1127862769178455e+149 -6.57669357529576e+152 inf
3121 1.21424327243701e+153 1.4629264144224735e+154 1.3838014027329285e+150 5.732892971421735e+149 7.374350956781282e+152 inf
3122 -1.3615133403046724e+153 -1.6403581344310813e+154 -1.5516364083877768e+150 -6.428209598776594e+149 -8.268752589911557e+152 inf
3123 1.5266451277980772e+153 1.8393097442679522e+154 1.7398273618452183e+150 7.207858031153217e+149 9.271632146866414e+152 inf
3124 -1.7118050020047124e+153 -2.0623912939184773e+154 -1.950843143833201e+150 -8.082066491289804e+149 -1.0396146423789418e+153 inf
3125 1.9194220788655916e+153 2.3125293945113315e+154 2.1874520744429897e+150 9.062303736742479e+149 1.1657047945047516e+153 inf
3126 -2.152220090794426e+153 -2.5930056125859142e+154 -2.4527582307735428e+150 -1.0161429518735839e+150 -1.3070878501883596e+153 inf
3127 2.4132531193746167e+153 2.907499521026782e+154 2.750242169378358e+150 1.139386328948515e+150 1.4656186164489432e+153 inf
3128 -2.7059456619150544e+153 -3.260136971450866e+154 -3.083806587753894e+150 -1.2775773371267774e+150 -1.6433768614498532e+153 inf
3129 3.0341375574950336e+153 3.655544221334002e+154 3.457827523902641e+150 1.432528906895165e+150 1.8426945990166314e+153 inf
3130 -3.402134361887735e+153 -4.0989086259714577e+154 -3.877211765659861e+150 -1.6062738508695485e+150 -2.0661866823714815e+153 inf
3131 3.814763832228096e+153 4.596046691491568e+154 4.3474612229370454e+150 1.8010915323023826e+150 2.3167851084425383e+153 inf
3132 -4.2774392624521086e+153 -5.1534803817111614e+154 -4.874745107383848e+150 -2.0195377680930715e+150 -2.5977774827880224e+153 inf
3133 4.796230500402871e+153 5.778522679904022e+154 5.465980866393698e+150 2.264478358598832e+150 2.912850149756519e+153 inf
3134 -5.37794357828201e+153 -6.479373527968654e+154 -6.1289249332293176e+150 -2.5391266841245433e+150 -3.2661365537091358e+153 inf
3135 6.0302100011153385e+153 7.265227401623396e+154 6.872274483818809e+150 2.847085861320638e+150 3.6622714657555476e+153 inf
3136 -6.761586864615015e+153 -8.146393932909679e+154 -7.705781535174312e+150 -3.1923960125395296e+150 -4.106451787404885e+153 inf
3137 7.581669115881004e+153 9.134433162452556e+154 8.640380882289297e+150 3.579587268278182e+150 4.604504728816359e+153 inf
3138 -8.501215429697704e+153 -1.0242307195855319e+155 -9.688333551924704e+150 -4.013739198047198e+150 -5.1629642560812764e+153 inf
3139 9.532289351792545e+153 1.1484550253811548e+155 1.0863387655253457e+151 4.5005474493402725e+150 5.78915681044913e+153 inf
3140 -1.0688417560726496e+154 -1.2877459346825294e+155 -1.2180958749594999e+151 -5.046398468943373e+150 -6.491297424051404e+153 inf
3141 1.1984767324647097e+154 1.4439308076004328e+155 1.3658332075407746e+151 5.658453286852229e+150 7.278597493065141e+153 inf
3142 -1.3438345480972054e+154 -1.6190586364783545e+155 -1.5314889321689372e+151 -6.344741461962495e+150 -8.161385622196544e+153 inf
3143 1.506822154941392e+154 1.8154269266623533e+155 1.7172362894727326e+151 7.1142664220066e+150 9.151243125843877e+153 inf
3144 -1.6895777905376646e+154 -2.0356118375177677e+155 -1.925512102595311e+151 -7.977123579695212e+150 -1.026115596358311e+154 inf
3145 1.8944990295746648e+154 2.282501979113344e+155 2.1590487459238567e+151 8.944632774629887e+150 1.1505685103221329e+154 inf
3146 -2.1242742377178764e+154 -2.559336307952102e+155 -2.42090999116149e+151 -1.002948677849617e+151 -1.29011575464118e+154 inf
3147 2.3819178403299877e+154 2.8697466189038657e+155 2.714531201007104e+151 1.124591781177866e+151 1.4465880522902433e+154 inf
3148 -2.6708098687754603e+154 -3.2178051907917966e+155 -3.043764397744387e+151 -1.2609884256534604e+151 -1.622038166343379e+154 inf
3149 2.99474030311646e+154 3.608078210696383e+155 3.412928797996194e+151 1.413928001471415e+151 1.818767830212042e+154 inf
3150 -3.357958792934245e+154 -4.0456856778512932e+155 -3.8268674766100717e+151 -1.5854169258603144e+151 -2.0393579441298873e+154 inf
3151 3.76523040856336e+154 4.536368573011633e+155 4.291010903050244e+151 1.777704965308415e+151 2.2867024340323394e+154 inf
3152 -4.2218981541408735e+154 -5.0865641744904885e+155 -4.811448183830718e+151 -1.9933147502934402e+151 -2.564046217026668e+154 inf
3153 4.733953062580124e+154 5.703490508936573e+155 5.395006945620116e+151 2.2350748697200258e+151 2.875027771521476e+154 inf
3154 -5.308112792046154e+154 -6.395241044764353e+155 -6.049342907007231e+151 -2.5061569792320103e+151 -3.2237268704949085e+154 inf
3155 5.951909755042612e+154 7.170890870521436e+155 6.783040314019962e+151 2.810117410223493e+151 3.6147181041146114e+154 inf
3156 -6.673789936275234e+154 -8.040615751149096e+155 -7.605724557013453e+151 -3.150943825418818e+151 -4.053130893873769e+154 inf
3157 7.483223695687425e+154 9.015825624037996e+155 8.528188446350805e+151 3.533107533095941e+151 4.5447167855701377e+154 inf
3158 -8.390830010294388e+154 -1.0109314286215395e+156 -9.562533803489774e+151 -3.961622146266137e+151 -5.0959249039457426e+154 inf
3159 9.408515784745344e+154 1.1335427236413864e+156 1.072233022500923e+152 4.4421093563583934e+151 5.713986558877792e+154 inf
3160 -1.0549632058235209e+155 -1.2710249873944408e+156 -1.2022793102408932e+152 -4.9808726842980495e+151 -6.407010113072127e+154 inf
3161 1.1829149157042603e+155 1.4251818523358275e+156 1.348098323312038e+152 5.584980176517865e+151 7.184087355828512e+154 inf
3162 -1.3263853090528616e+155 -1.598035705333509e+156 -1.5116030641437312e+152 -6.262357130795313e+151 -8.0554127783994e+154 inf
3163 1.4872565767114704e+155 1.7918542194003516e+156 1.694938554567001e+152 7.021890068385962e+151 9.032417315715764e+154 inf
3164 -1.667639191926056e+155 -2.0091801033399008e+156 -1.9005099763971768e+152 -7.87354331646604e+151 -1.0127918309042053e+155 inf
3165 1.8698995976854444e+155 2.2528644595919642e+156 2.1310142250601265e+152 8.828489730332204e+151 1.1356287656921572e+155 inf
3166 -2.0966912521322016e+155 -2.5261041879001578e+156 -2.3894752902153066e+152 -9.899257270304241e+151 -1.2733640360390114e+155 inf
3167 2.3509894393309645e+155 2.8324839255009815e+156 2.6792839275337477e+152 1.1099893356276612e+152 1.4278045935982102e+155 inf
3168 -2.636130302077121e+155 -3.1760230740485103e+156 -3.004242142087191e+152 -1.2446149156089863e+152 -1.600976547006655e+155 inf
3169 2.9558546088181515e+155 3.561228530221728e+156 3.3686130669250183e+152 1.3955686225403548e+152 1.795151742442543e+155 inf
3170 -3.3143568288666025e+155 -3.993153811788558e+156 -3.777176891199131e+152 -1.5648308209983117e+152 -2.0128775680192205e+155 inf
3171 3.7163401597235173e+155 4.477465354802334e+156 4.2352935715564e+152 1.7546220650109815e+152 2.257010373018418e+155 inf
3172 -4.1670782284165016e+155 -5.020516851685156e+156 -4.748973149513375e+152 -1.9674322295487692e+152 -2.530752940391519e+155 inf
3173 4.672484276314235e+155 5.629432605440541e+156 5.324954597305853e+152 2.206053175242111e+152 2.8376965041303546e+155 inf
3174 -5.239188735052762e+155 -6.312200993521222e+156 -5.9707942265948685e+152 -2.473615374854283e+152 -3.181867862734922e+155 inf
3175 5.874626211296018e+155 7.077779267506166e+156 6.6949648198645385e+152 2.7736289820140467e+152 3.567782206860048e+155 inf
3176 -6.587133021482586e+155 -7.936211063455847e+156 -7.506966785017866e+152 -3.1100298809879928e+152 -4.000502354188326e+155 inf
3177 7.386056556121678e+155 8.898758164566402e+156 8.41745279141008e+152 3.487231321622143e+152 4.485705168632222e+155 inf
3178 -8.281877908387626e+155 -9.978048244719211e+156 -9.438367522422691e+152 -3.9101818168509768e+152 -5.029756035220947e+155 inf
3179 9.286349375783132e+155 1.1188240531177015e+157 1.058310437799301e+153 4.384430062333753e+152 5.6397923677080075e+155 inf
3180 -1.0412648638754961e+156 -1.2545211559757728e+157 -1.186668118288603e+153 -4.916197729899223e+152 -6.323817244440542e+155 inf
3181 1.1675551638937014e+156 1.4066763459412502e+157 1.330593720582444e+153 5.512461089777628e+152 7.090804400895653e+155 inf
3182 -1.3091626425011262e+156 -1.5772857498696875e+157 -1.491975407417866e+153 -6.181042532423799e+152 -7.950815956290523e+155 inf
3183 1.4679450509257666e+156 1.768587595803565e+157 1.6729303482398332e+153 6.930713190607455e+152 8.915134418715227e+155 inf
3184 -1.645985458629161e+156 -1.983091576328938e+157 -1.8758324943877283e+153 -7.771308008072207e+152 -9.996410700574722e+155 inf
3185 1.8456195811349673e+156 2.2236117732805666e+157 2.1033437230087e+153 8.713854764351407e+152 1.1208830086149634e+156 inf
3186 -2.0694664223252527e+156 -2.493303575735523e+157 -2.3584487582746173e+153 -9.770718748418807e+152 -1.2568298328614212e+156 inf
3187 2.320462633203183e+156 2.795705075623006e+157 2.644494328036286e+153 1.095576497915271e+153 1.4092650317916067e+156 inf
3188 -2.6019010378733533e+156 -3.134783484020205e+157 -2.965233069609775e+153 -1.2284540100783495e+153 -1.580188405704099e+156 inf
3189 2.917473832164813e+156 3.5149871770705327e+157 3.3248727606976977e+153 1.3774476339618377e+153 1.771842301619579e+156 inf
3190 -3.2713210216186025e+156 -3.941304054315566e+157 -3.728131521305492e+153 -1.5445120197752057e+153 -1.9867410306745937e+156 inf
3191 3.668084734300145e+156 4.4193269750447645e+157 4.180299710848176e+153 1.7318388884003035e+153 2.227703853417417e+156 inf
3192 -4.1129701209661104e+156 -4.9553271311238523e+157 -4.687309332477061e+153 -1.9418857846195917e+153 -2.4978919657413764e+156 inf
3193 4.611813641537296e+156 5.556336318881063e+157 5.255811855143085e+153 2.1774083176933946e+153 2.800849970674358e+156 inf
3194 -5.171159633727961e+156 -6.230239189378203e+157 -5.893265474344887e+153 -2.4414963122504367e+153 -3.140552380093887e+156 inf
3195 5.798346168338268e+156 6.985876687298992e+157 6.608032956339805e+153 2.7376143437567157e+153 3.521455756424829e+156 inf
3196 -6.5016013175452605e+156 -7.833162035472046e+157 -7.409491349433055e+153 -3.069647190347093e+153 -3.948557178367025e+156 inf
3197 7.290151099140226e+156 8.783210786631314e+157 8.308155001656494e+153 3.441950797304618e+153 4.427459797666996e+156 inf
3198 -8.174340512832485e+156 -9.848486648565508e+157 -9.315813498699755e+153 -3.859409422789773e+153 -4.9644463469728e+156 inf
3199 9.165769256499394e+156 1.104296499573969e+158 1.0445686331713435e+154 4.327499714517441e+153 5.566561563124398e+156 inf
3200 -1.0277443902844904e+157 -1.2382316212501002e+158 -1.171259632406435e+154 -4.85236255800268e+153 -6.241704607191188e+156 inf
3201 1.1523948532877055e+157 1.388411127315132e+158 1.3133164092243049e+154 5.440883638956636e+153 6.998732693717982e+156 inf
3202 -1.292163606474523e+157 -1.5568052255896282e+158 -1.4726026092045927e+154 -6.1007837767278504e+153 -7.847577288691665e+156 inf
3203 1.448884278798853e+157 1.745623081478714e+158 1.6512079110601535e+154 6.84072021388148e+153 8.799374400635157e+156 inf
3204 -1.6246128917668542e+157 -1.9573418000553965e+158 -1.8514754411715758e+154 -7.670400190728126e+153 -9.866610674115606e+156 inf
3205 1.8216548324226128e+157 2.1947389232495058e+158 2.0760325131078047e+154 8.600708294798333e+153 1.106328720227501e+157 inf
3206 -2.0425950977648707e+157 -2.4609288684736044e+158 -2.3278250954023967e+154 -9.643849255952148e+153 -1.2405103207438624e+157 inf
3207 2.2903322073724583e+157 2.7594037867246947e+158 2.6101564597722185e+154 1.081350806046782e+154 1.3909661999515177e+157 inf
3208 -2.568116229137893e+157 -3.094079376180187e+158 -2.9267305168013966e+154 -1.2125029484635057e+154 -1.5596701914155393e+157 inf
3209 2.8795914169708585e+157 3.469346252317317e+158 3.2817004076163807e+154 1.3595619403174438e+154 1.7488355260357877e+157 inf
3210 -3.228844019834532e+157 -3.8901275484818915e+158 -3.6797229890228785e+154 -1.5244570513431902e+154 -1.9609438674653946e+157 inf
3211 3.620455889324926e+157 4.3619435025690323e+158 4.1260199269009354e+154 1.709351543665229e+154 2.1987778691038353e+157 inf
3212 -4.0595645890688496e+157 -4.890983877130005e+158 -4.6264461993383776e+154 -1.9166710516745017e+154 -2.465457679780447e+157 inf
3213 4.5519307945208514e+157 5.48418916298584e+158 5.1875669082019933e+154 2.1491354039731917e+154 2.764481877046403e+157 inf
3214 -5.1040138673735786e+157 -6.149341631659636e+158 -5.816743406833487e+154 -2.409794304857725e+154 -3.0997733650811196e+157 inf
3215 5.72305659604953e+157 6.895167431145727e+158 6.522229873786727e+154 2.7020673434484814e+154 3.4757308393470874e+157 inf
3216 -6.417180213978934e+157 -7.731451064412765e+158 -7.313281599552547e+154 -3.029788855344477e+154 -3.8972864931602237e+157 inf
3217 7.195490942219704e+157 8.669163752485835e+158 8.200276406894536e+154 3.397258225346225e+154 4.369970723228411e+157 inf
3218 -8.06819945414315e+157 -9.720607366105394e+158 -9.194850797702547e+154 -3.8092962911668634e+154 -4.89998468303231e+157 inf
3219 9.04675482945682e+157 1.0899575814205558e+159 1.0310052612486302e+155 4.271308588095012e+154 5.494281635876224e+157 inf
3220 -1.0143994754897639e+158 -1.2221536006470043e+159 -1.1560512205243555e+155 -4.7893562643155434e+154 -6.160658174883601e+157 inf
3221 1.1374313942093889e+158 1.370383076401686e+159 1.2962634379356283e+155 5.370235597229212e+154 6.907856506650792e+157 inf
3222 -1.2753852972059412e+158 -1.536590634020114e+159 -1.453481360251963e+155 -6.021567153946022e+154 -7.745679140423992e+157 inf
3223 1.4300710043789242e+158 1.7229567536386142e+159 1.6297675324117542e+155 6.751895765651139e+154 8.68511748740519e+157 inf
3224 -1.6035178404876045e+158 -1.931926375955017e+159 -1.827434656088753e+155 -7.57080262740978e+154 -9.738496057287472e+157 inf
3225 1.7980012579016834e+158 2.1662409774526058e+159 2.0490759300698533e+155 8.489030994047852e+154 1.0919634143732882e+158 inf
3226 -2.0160726883044754e+158 -2.4289745358826777e+159 -2.297599070479499e+155 -9.518627121119701e+154 -1.2244027119952638e+158 inf
3227 2.26059301497414e+158 2.7235738578375747e+159 2.576264457163599e+155 1.0673098299964034e+155 1.3729049722803705e+158 inf

C:\Users\alirm\AppData\Local\Temp\ipykernel_55216\4284080532.py:22: RuntimeWarning: overflow encountered in scalar add
  dj_dw_val_2 += (y_hat - y_train[i]) * X_train[i, 1]
C:\Users\alirm\AppData\Local\Temp\ipykernel_55216\4284080532.py:24: RuntimeWarning: invalid value encountered in scalar multiply
  dj_dw_val_4 += (y_hat - y_train[i]) * X_train[i, 3]
C:\Users\alirm\AppData\Local\Temp\ipykernel_55216\4284080532.py:23: RuntimeWarning: invalid value encountered in scalar multiply
  dj_dw_val_3 += (y_hat - y_train[i]) * X_train[i, 2]
C:\Users\alirm\AppData\Local\Temp\ipykernel_55216\4284080532.py:9: RuntimeWarning: invalid value encountered in scalar subtract
  w_2 = w_2 - learning_rate * dj_dw_2

6110 -4.853027066619022e+301 -5.846951469136097e+302 -5.530708561234071e+298 -2.291294124652645e+298 -2.9473438811137275e+301 inf
6111 5.441628742813762e+301 inf 6.201503157060398e+298 2.569194813009106e+298 3.3048138735394007e+301 inf
6112 -inf nan nan nan -inf nan
6113 nan nan nan nan nan nan
6114 nan nan nan nan nan nan
6115 nan nan nan nan nan nan
6116 nan nan nan nan nan nan
6117 nan nan nan nan nan nan
6118 nan nan nan nan nan nan
6119 nan nan nan nan nan nan
6120 nan nan nan nan nan nan
6121 nan nan nan nan nan nan
6122 nan nan nan nan nan nan
6123 nan nan nan nan nan nan
6124 nan nan nan nan nan nan
6125 nan nan nan nan nan nan
6126 nan nan nan nan nan nan
6127 nan nan nan nan nan nan
6128 nan nan nan nan nan nan
6129 nan nan nan nan nan nan
6130 nan nan nan nan nan nan
6131 nan nan nan nan nan nan
6132 nan nan nan nan nan nan
6133 nan nan nan nan nan nan
6134 nan nan nan nan nan nan
6135 nan nan nan nan nan nan
6136 nan nan nan nan nan nan
6137 nan nan nan nan nan nan
6138 nan nan nan nan nan nan
6139 nan nan nan nan nan nan
6140 nan nan nan nan nan nan
6141 nan nan nan nan nan nan
6142 nan nan nan nan nan nan
6143 nan nan nan nan nan nan
6144 nan nan nan nan nan nan
6145 nan nan nan nan nan nan
6146 nan nan nan nan nan nan
6147 nan nan nan nan nan nan
6148 nan nan nan nan nan nan
6149 nan nan nan nan nan nan
6150 nan nan nan nan nan nan
6151 nan nan nan nan nan nan
6152 nan nan nan nan nan nan
6153 nan nan nan nan nan nan
6154 nan nan nan nan nan nan
6155 nan nan nan nan nan nan
6156 nan nan nan nan nan nan
6157 nan nan nan nan nan nan
6158 nan nan nan nan nan nan
6159 nan nan nan nan nan nan
6160 nan nan nan nan nan nan
6161 nan nan nan nan nan nan
6162 nan nan nan nan nan nan
6163 nan nan nan nan nan nan
6164 nan nan nan nan nan nan
6165 nan nan nan nan nan nan
6166 nan nan nan nan nan nan
6167 nan nan nan nan nan nan
6168 nan nan nan nan nan nan
6169 nan nan nan nan nan nan
6170 nan nan nan nan nan nan
6171 nan nan nan nan nan nan
6172 nan nan nan nan nan nan
6173 nan nan nan nan nan nan
6174 nan nan nan nan nan nan
6175 nan nan nan nan nan nan
6176 nan nan nan nan nan nan
6177 nan nan nan nan nan nan
6178 nan nan nan nan nan nan
6179 nan nan nan nan nan nan
6180 nan nan nan nan nan nan
6181 nan nan nan nan nan nan
6182 nan nan nan nan nan nan
6183 nan nan nan nan nan nan
6184 nan nan nan nan nan nan
6185 nan nan nan nan nan nan
6186 nan nan nan nan nan nan
6187 nan nan nan nan nan nan
6188 nan nan nan nan nan nan
6189 nan nan nan nan nan nan
6190 nan nan nan nan nan nan
6191 nan nan nan nan nan nan
6192 nan nan nan nan nan nan
6193 nan nan nan nan nan nan
6194 nan nan nan nan nan nan
6195 nan nan nan nan nan nan
6196 nan nan nan nan nan nan
6197 nan nan nan nan nan nan
6198 nan nan nan nan nan nan
6199 nan nan nan nan nan nan
6200 nan nan nan nan nan nan
6201 nan nan nan nan nan nan
6202 nan nan nan nan nan nan
6203 nan nan nan nan nan nan
6204 nan nan nan nan nan nan
6205 nan nan nan nan nan nan
6206 nan nan nan nan nan nan
6207 nan nan nan nan nan nan
6208 nan nan nan nan nan nan
6209 nan nan nan nan nan nan
6210 nan nan nan nan nan nan
6211 nan nan nan nan nan nan
6212 nan nan nan nan nan nan
6213 nan nan nan nan nan nan
6214 nan nan nan nan nan nan
6215 nan nan nan nan nan nan
6216 nan nan nan nan nan nan
6217 nan nan nan nan nan nan
6218 nan nan nan nan nan nan
6219 nan nan nan nan nan nan
6220 nan nan nan nan nan nan
6221 nan nan nan nan nan nan
6222 nan nan nan nan nan nan
6223 nan nan nan nan nan nan
6224 nan nan nan nan nan nan
6225 nan nan nan nan nan nan
6226 nan nan nan nan nan nan
6227 nan nan nan nan nan nan
6228 nan nan nan nan nan nan
6229 nan nan nan nan nan nan
6230 nan nan nan nan nan nan
6231 nan nan nan nan nan nan
6232 nan nan nan nan nan nan
6233 nan nan nan nan nan nan
6234 nan nan nan nan nan nan
6235 nan nan nan nan nan nan
6236 nan nan nan nan nan nan
6237 nan nan nan nan nan nan
6238 nan nan nan nan nan nan
6239 nan nan nan nan nan nan
6240 nan nan nan nan nan nan
6241 nan nan nan nan nan nan
6242 nan nan nan nan nan nan
6243 nan nan nan nan nan nan
6244 nan nan nan nan nan nan
6245 nan nan nan nan nan nan
6246 nan nan nan nan nan nan
6247 nan nan nan nan nan nan
6248 nan nan nan nan nan nan
6249 nan nan nan nan nan nan
6250 nan nan nan nan nan nan
6251 nan nan nan nan nan nan
6252 nan nan nan nan nan nan
6253 nan nan nan nan nan nan
6254 nan nan nan nan nan nan
6255 nan nan nan nan nan nan
6256 nan nan nan nan nan nan
6257 nan nan nan nan nan nan
6258 nan nan nan nan nan nan
6259 nan nan nan nan nan nan
6260 nan nan nan nan nan nan
6261 nan nan nan nan nan nan
6262 nan nan nan nan nan nan
6263 nan nan nan nan nan nan
6264 nan nan nan nan nan nan
6265 nan nan nan nan nan nan
6266 nan nan nan nan nan nan
6267 nan nan nan nan nan nan
6268 nan nan nan nan nan nan
6269 nan nan nan nan nan nan
6270 nan nan nan nan nan nan
6271 nan nan nan nan nan nan
6272 nan nan nan nan nan nan
6273 nan nan nan nan nan nan
6274 nan nan nan nan nan nan
6275 nan nan nan nan nan nan
6276 nan nan nan nan nan nan
6277 nan nan nan nan nan nan
6278 nan nan nan nan nan nan
6279 nan nan nan nan nan nan
6280 nan nan nan nan nan nan
6281 nan nan nan nan nan nan
6282 nan nan nan nan nan nan
6283 nan nan nan nan nan nan
6284 nan nan nan nan nan nan
6285 nan nan nan nan nan nan
6286 nan nan nan nan nan nan
6287 nan nan nan nan nan nan
6288 nan nan nan nan nan nan
6289 nan nan nan nan nan nan
6290 nan nan nan nan nan nan
6291 nan nan nan nan nan nan
6292 nan nan nan nan nan nan
6293 nan nan nan nan nan nan
6294 nan nan nan nan nan nan
6295 nan nan nan nan nan nan
6296 nan nan nan nan nan nan
6297 nan nan nan nan nan nan
6298 nan nan nan nan nan nan
6299 nan nan nan nan nan nan
6300 nan nan nan nan nan nan
6301 nan nan nan nan nan nan
6302 nan nan nan nan nan nan
6303 nan nan nan nan nan nan
6304 nan nan nan nan nan nan
6305 nan nan nan nan nan nan
6306 nan nan nan nan nan nan
6307 nan nan nan nan nan nan
6308 nan nan nan nan nan nan
6309 nan nan nan nan nan nan
6310 nan nan nan nan nan nan
6311 nan nan nan nan nan nan
6312 nan nan nan nan nan nan
6313 nan nan nan nan nan nan
6314 nan nan nan nan nan nan
6315 nan nan nan nan nan nan
6316 nan nan nan nan nan nan
6317 nan nan nan nan nan nan
6318 nan nan nan nan nan nan
6319 nan nan nan nan nan nan
6320 nan nan nan nan nan nan
6321 nan nan nan nan nan nan
6322 nan nan nan nan nan nan
6323 nan nan nan nan nan nan
6324 nan nan nan nan nan nan
6325 nan nan nan nan nan nan
6326 nan nan nan nan nan nan
6327 nan nan nan nan nan nan
6328 nan nan nan nan nan nan
6329 nan nan nan nan nan nan
6330 nan nan nan nan nan nan
6331 nan nan nan nan nan nan
6332 nan nan nan nan nan nan
6333 nan nan nan nan nan nan
6334 nan nan nan nan nan nan
6335 nan nan nan nan nan nan
6336 nan nan nan nan nan nan
6337 nan nan nan nan nan nan
6338 nan nan nan nan nan nan
6339 nan nan nan nan nan nan
6340 nan nan nan nan nan nan
6341 nan nan nan nan nan nan
6342 nan nan nan nan nan nan
6343 nan nan nan nan nan nan
6344 nan nan nan nan nan nan
6345 nan nan nan nan nan nan
6346 nan nan nan nan nan nan
6347 nan nan nan nan nan nan
6348 nan nan nan nan nan nan
6349 nan nan nan nan nan nan
6350 nan nan nan nan nan nan
6351 nan nan nan nan nan nan
6352 nan nan nan nan nan nan
6353 nan nan nan nan nan nan
6354 nan nan nan nan nan nan
6355 nan nan nan nan nan nan
6356 nan nan nan nan nan nan
6357 nan nan nan nan nan nan
6358 nan nan nan nan nan nan
6359 nan nan nan nan nan nan
6360 nan nan nan nan nan nan
6361 nan nan nan nan nan nan
6362 nan nan nan nan nan nan
6363 nan nan nan nan nan nan
6364 nan nan nan nan nan nan
6365 nan nan nan nan nan nan
6366 nan nan nan nan nan nan
6367 nan nan nan nan nan nan
6368 nan nan nan nan nan nan
6369 nan nan nan nan nan nan
6370 nan nan nan nan nan nan
6371 nan nan nan nan nan nan
6372 nan nan nan nan nan nan
6373 nan nan nan nan nan nan
6374 nan nan nan nan nan nan
6375 nan nan nan nan nan nan
6376 nan nan nan nan nan nan
6377 nan nan nan nan nan nan
6378 nan nan nan nan nan nan
6379 nan nan nan nan nan nan
6380 nan nan nan nan nan nan
6381 nan nan nan nan nan nan
6382 nan nan nan nan nan nan
6383 nan nan nan nan nan nan
6384 nan nan nan nan nan nan
6385 nan nan nan nan nan nan
6386 nan nan nan nan nan nan
6387 nan nan nan nan nan nan
6388 nan nan nan nan nan nan
6389 nan nan nan nan nan nan
6390 nan nan nan nan nan nan
6391 nan nan nan nan nan nan
6392 nan nan nan nan nan nan
6393 nan nan nan nan nan nan
6394 nan nan nan nan nan nan
6395 nan nan nan nan nan nan
6396 nan nan nan nan nan nan
6397 nan nan nan nan nan nan
6398 nan nan nan nan nan nan
6399 nan nan nan nan nan nan
6400 nan nan nan nan nan nan
6401 nan nan nan nan nan nan
6402 nan nan nan nan nan nan
6403 nan nan nan nan nan nan
6404 nan nan nan nan nan nan
6405 nan nan nan nan nan nan
6406 nan nan nan nan nan nan
6407 nan nan nan nan nan nan
6408 nan nan nan nan nan nan
6409 nan nan nan nan nan nan
6410 nan nan nan nan nan nan
6411 nan nan nan nan nan nan
6412 nan nan nan nan nan nan
6413 nan nan nan nan nan nan
6414 nan nan nan nan nan nan
6415 nan nan nan nan nan nan
6416 nan nan nan nan nan nan
6417 nan nan nan nan nan nan
6418 nan nan nan nan nan nan
6419 nan nan nan nan nan nan
6420 nan nan nan nan nan nan
6421 nan nan nan nan nan nan
6422 nan nan nan nan nan nan
6423 nan nan nan nan nan nan
6424 nan nan nan nan nan nan
6425 nan nan nan nan nan nan
6426 nan nan nan nan nan nan
6427 nan nan nan nan nan nan
6428 nan nan nan nan nan nan
6429 nan nan nan nan nan nan
6430 nan nan nan nan nan nan
6431 nan nan nan nan nan nan
6432 nan nan nan nan nan nan
6433 nan nan nan nan nan nan
6434 nan nan nan nan nan nan
6435 nan nan nan nan nan nan
6436 nan nan nan nan nan nan
6437 nan nan nan nan nan nan
6438 nan nan nan nan nan nan
6439 nan nan nan nan nan nan
6440 nan nan nan nan nan nan
6441 nan nan nan nan nan nan
6442 nan nan nan nan nan nan
6443 nan nan nan nan nan nan
6444 nan nan nan nan nan nan
6445 nan nan nan nan nan nan
6446 nan nan nan nan nan nan
6447 nan nan nan nan nan nan
6448 nan nan nan nan nan nan
6449 nan nan nan nan nan nan
6450 nan nan nan nan nan nan
6451 nan nan nan nan nan nan
6452 nan nan nan nan nan nan
6453 nan nan nan nan nan nan
6454 nan nan nan nan nan nan
6455 nan nan nan nan nan nan
6456 nan nan nan nan nan nan
6457 nan nan nan nan nan nan
6458 nan nan nan nan nan nan
6459 nan nan nan nan nan nan
6460 nan nan nan nan nan nan
6461 nan nan nan nan nan nan
6462 nan nan nan nan nan nan
6463 nan nan nan nan nan nan
6464 nan nan nan nan nan nan
6465 nan nan nan nan nan nan
6466 nan nan nan nan nan nan
6467 nan nan nan nan nan nan
6468 nan nan nan nan nan nan
6469 nan nan nan nan nan nan
6470 nan nan nan nan nan nan
6471 nan nan nan nan nan nan
6472 nan nan nan nan nan nan
6473 nan nan nan nan nan nan
6474 nan nan nan nan nan nan
6475 nan nan nan nan nan nan
6476 nan nan nan nan nan nan
6477 nan nan nan nan nan nan
6478 nan nan nan nan nan nan
6479 nan nan nan nan nan nan
6480 nan nan nan nan nan nan
6481 nan nan nan nan nan nan
6482 nan nan nan nan nan nan
6483 nan nan nan nan nan nan
6484 nan nan nan nan nan nan
6485 nan nan nan nan nan nan
6486 nan nan nan nan nan nan
6487 nan nan nan nan nan nan
6488 nan nan nan nan nan nan
6489 nan nan nan nan nan nan
6490 nan nan nan nan nan nan
6491 nan nan nan nan nan nan
6492 nan nan nan nan nan nan
6493 nan nan nan nan nan nan
6494 nan nan nan nan nan nan
6495 nan nan nan nan nan nan
6496 nan nan nan nan nan nan
6497 nan nan nan nan nan nan
6498 nan nan nan nan nan nan
6499 nan nan nan nan nan nan
6500 nan nan nan nan nan nan
6501 nan nan nan nan nan nan
6502 nan nan nan nan nan nan
6503 nan nan nan nan nan nan
6504 nan nan nan nan nan nan
6505 nan nan nan nan nan nan
6506 nan nan nan nan nan nan
6507 nan nan nan nan nan nan
6508 nan nan nan nan nan nan
6509 nan nan nan nan nan nan
6510 nan nan nan nan nan nan
6511 nan nan nan nan nan nan
6512 nan nan nan nan nan nan
6513 nan nan nan nan nan nan
6514 nan nan nan nan nan nan
6515 nan nan nan nan nan nan
6516 nan nan nan nan nan nan
6517 nan nan nan nan nan nan
6518 nan nan nan nan nan nan
6519 nan nan nan nan nan nan
6520 nan nan nan nan nan nan
6521 nan nan nan nan nan nan
6522 nan nan nan nan nan nan
6523 nan nan nan nan nan nan
6524 nan nan nan nan nan nan
6525 nan nan nan nan nan nan
6526 nan nan nan nan nan nan
6527 nan nan nan nan nan nan
6528 nan nan nan nan nan nan
6529 nan nan nan nan nan nan
6530 nan nan nan nan nan nan
6531 nan nan nan nan nan nan
6532 nan nan nan nan nan nan
6533 nan nan nan nan nan nan
6534 nan nan nan nan nan nan
6535 nan nan nan nan nan nan
6536 nan nan nan nan nan nan
6537 nan nan nan nan nan nan
6538 nan nan nan nan nan nan
6539 nan nan nan nan nan nan
6540 nan nan nan nan nan nan
6541 nan nan nan nan nan nan
6542 nan nan nan nan nan nan
6543 nan nan nan nan nan nan
6544 nan nan nan nan nan nan
6545 nan nan nan nan nan nan
6546 nan nan nan nan nan nan
6547 nan nan nan nan nan nan
6548 nan nan nan nan nan nan
6549 nan nan nan nan nan nan
6550 nan nan nan nan nan nan
6551 nan nan nan nan nan nan
6552 nan nan nan nan nan nan
6553 nan nan nan nan nan nan
6554 nan nan nan nan nan nan
6555 nan nan nan nan nan nan
6556 nan nan nan nan nan nan
6557 nan nan nan nan nan nan
6558 nan nan nan nan nan nan
6559 nan nan nan nan nan nan
6560 nan nan nan nan nan nan
6561 nan nan nan nan nan nan
6562 nan nan nan nan nan nan
6563 nan nan nan nan nan nan
6564 nan nan nan nan nan nan
6565 nan nan nan nan nan nan
6566 nan nan nan nan nan nan
6567 nan nan nan nan nan nan
6568 nan nan nan nan nan nan
6569 nan nan nan nan nan nan
6570 nan nan nan nan nan nan
6571 nan nan nan nan nan nan
6572 nan nan nan nan nan nan
6573 nan nan nan nan nan nan
6574 nan nan nan nan nan nan
6575 nan nan nan nan nan nan
6576 nan nan nan nan nan nan
6577 nan nan nan nan nan nan
6578 nan nan nan nan nan nan
6579 nan nan nan nan nan nan
6580 nan nan nan nan nan nan
6581 nan nan nan nan nan nan
6582 nan nan nan nan nan nan
6583 nan nan nan nan nan nan
6584 nan nan nan nan nan nan
6585 nan nan nan nan nan nan
6586 nan nan nan nan nan nan
6587 nan nan nan nan nan nan
6588 nan nan nan nan nan nan
6589 nan nan nan nan nan nan
6590 nan nan nan nan nan nan
6591 nan nan nan nan nan nan
6592 nan nan nan nan nan nan
6593 nan nan nan nan nan nan
6594 nan nan nan nan nan nan
6595 nan nan nan nan nan nan
6596 nan nan nan nan nan nan
6597 nan nan nan nan nan nan
6598 nan nan nan nan nan nan
6599 nan nan nan nan nan nan
6600 nan nan nan nan nan nan
6601 nan nan nan nan nan nan
6602 nan nan nan nan nan nan
6603 nan nan nan nan nan nan
6604 nan nan nan nan nan nan
6605 nan nan nan nan nan nan
6606 nan nan nan nan nan nan
6607 nan nan nan nan nan nan
6608 nan nan nan nan nan nan
6609 nan nan nan nan nan nan
6610 nan nan nan nan nan nan
6611 nan nan nan nan nan nan
6612 nan nan nan nan nan nan
6613 nan nan nan nan nan nan
6614 nan nan nan nan nan nan
6615 nan nan nan nan nan nan
6616 nan nan nan nan nan nan
6617 nan nan nan nan nan nan
6618 nan nan nan nan nan nan
6619 nan nan nan nan nan nan
6620 nan nan nan nan nan nan
6621 nan nan nan nan nan nan
6622 nan nan nan nan nan nan
6623 nan nan nan nan nan nan
6624 nan nan nan nan nan nan
6625 nan nan nan nan nan nan
6626 nan nan nan nan nan nan
6627 nan nan nan nan nan nan
6628 nan nan nan nan nan nan
6629 nan nan nan nan nan nan
6630 nan nan nan nan nan nan
6631 nan nan nan nan nan nan
6632 nan nan nan nan nan nan
6633 nan nan nan nan nan nan
6634 nan nan nan nan nan nan
6635 nan nan nan nan nan nan
6636 nan nan nan nan nan nan
6637 nan nan nan nan nan nan
6638 nan nan nan nan nan nan
6639 nan nan nan nan nan nan
6640 nan nan nan nan nan nan
6641 nan nan nan nan nan nan
6642 nan nan nan nan nan nan
6643 nan nan nan nan nan nan
6644 nan nan nan nan nan nan
6645 nan nan nan nan nan nan
6646 nan nan nan nan nan nan
6647 nan nan nan nan nan nan
6648 nan nan nan nan nan nan
6649 nan nan nan nan nan nan
6650 nan nan nan nan nan nan
6651 nan nan nan nan nan nan
6652 nan nan nan nan nan nan
6653 nan nan nan nan nan nan
6654 nan nan nan nan nan nan
6655 nan nan nan nan nan nan
6656 nan nan nan nan nan nan
6657 nan nan nan nan nan nan
6658 nan nan nan nan nan nan
6659 nan nan nan nan nan nan
6660 nan nan nan nan nan nan
6661 nan nan nan nan nan nan
6662 nan nan nan nan nan nan
6663 nan nan nan nan nan nan
6664 nan nan nan nan nan nan
6665 nan nan nan nan nan nan
6666 nan nan nan nan nan nan
6667 nan nan nan nan nan nan
6668 nan nan nan nan nan nan
6669 nan nan nan nan nan nan
6670 nan nan nan nan nan nan
6671 nan nan nan nan nan nan
6672 nan nan nan nan nan nan
6673 nan nan nan nan nan nan
6674 nan nan nan nan nan nan
6675 nan nan nan nan nan nan
6676 nan nan nan nan nan nan
6677 nan nan nan nan nan nan
6678 nan nan nan nan nan nan
6679 nan nan nan nan nan nan
6680 nan nan nan nan nan nan
6681 nan nan nan nan nan nan
6682 nan nan nan nan nan nan
6683 nan nan nan nan nan nan
6684 nan nan nan nan nan nan
6685 nan nan nan nan nan nan
6686 nan nan nan nan nan nan
6687 nan nan nan nan nan nan
6688 nan nan nan nan nan nan
6689 nan nan nan nan nan nan
6690 nan nan nan nan nan nan
6691 nan nan nan nan nan nan
6692 nan nan nan nan nan nan
6693 nan nan nan nan nan nan
6694 nan nan nan nan nan nan
6695 nan nan nan nan nan nan
6696 nan nan nan nan nan nan
6697 nan nan nan nan nan nan
6698 nan nan nan nan nan nan
6699 nan nan nan nan nan nan
6700 nan nan nan nan nan nan
6701 nan nan nan nan nan nan
6702 nan nan nan nan nan nan
6703 nan nan nan nan nan nan
6704 nan nan nan nan nan nan
6705 nan nan nan nan nan nan
6706 nan nan nan nan nan nan
6707 nan nan nan nan nan nan
6708 nan nan nan nan nan nan
6709 nan nan nan nan nan nan
6710 nan nan nan nan nan nan
6711 nan nan nan nan nan nan
6712 nan nan nan nan nan nan
6713 nan nan nan nan nan nan
6714 nan nan nan nan nan nan
6715 nan nan nan nan nan nan
6716 nan nan nan nan nan nan
6717 nan nan nan nan nan nan
6718 nan nan nan nan nan nan
6719 nan nan nan nan nan nan
6720 nan nan nan nan nan nan
6721 nan nan nan nan nan nan
6722 nan nan nan nan nan nan
6723 nan nan nan nan nan nan
6724 nan nan nan nan nan nan
6725 nan nan nan nan nan nan
6726 nan nan nan nan nan nan
6727 nan nan nan nan nan nan
6728 nan nan nan nan nan nan
6729 nan nan nan nan nan nan
6730 nan nan nan nan nan nan
6731 nan nan nan nan nan nan
6732 nan nan nan nan nan nan
6733 nan nan nan nan nan nan
6734 nan nan nan nan nan nan
6735 nan nan nan nan nan nan
6736 nan nan nan nan nan nan
6737 nan nan nan nan nan nan
6738 nan nan nan nan nan nan
6739 nan nan nan nan nan nan
6740 nan nan nan nan nan nan
6741 nan nan nan nan nan nan
6742 nan nan nan nan nan nan
6743 nan nan nan nan nan nan
6744 nan nan nan nan nan nan
6745 nan nan nan nan nan nan
6746 nan nan nan nan nan nan
6747 nan nan nan nan nan nan
6748 nan nan nan nan nan nan
6749 nan nan nan nan nan nan
6750 nan nan nan nan nan nan
6751 nan nan nan nan nan nan
6752 nan nan nan nan nan nan
6753 nan nan nan nan nan nan
6754 nan nan nan nan nan nan
6755 nan nan nan nan nan nan
6756 nan nan nan nan nan nan
6757 nan nan nan nan nan nan
6758 nan nan nan nan nan nan
6759 nan nan nan nan nan nan
6760 nan nan nan nan nan nan
6761 nan nan nan nan nan nan
6762 nan nan nan nan nan nan
6763 nan nan nan nan nan nan
6764 nan nan nan nan nan nan
6765 nan nan nan nan nan nan
6766 nan nan nan nan nan nan
6767 nan nan nan nan nan nan
6768 nan nan nan nan nan nan
6769 nan nan nan nan nan nan
6770 nan nan nan nan nan nan
6771 nan nan nan nan nan nan
6772 nan nan nan nan nan nan
6773 nan nan nan nan nan nan
6774 nan nan nan nan nan nan
6775 nan nan nan nan nan nan
6776 nan nan nan nan nan nan
6777 nan nan nan nan nan nan
6778 nan nan nan nan nan nan
6779 nan nan nan nan nan nan
6780 nan nan nan nan nan nan
6781 nan nan nan nan nan nan
6782 nan nan nan nan nan nan
6783 nan nan nan nan nan nan
6784 nan nan nan nan nan nan
6785 nan nan nan nan nan nan
6786 nan nan nan nan nan nan
6787 nan nan nan nan nan nan
6788 nan nan nan nan nan nan
6789 nan nan nan nan nan nan
6790 nan nan nan nan nan nan
6791 nan nan nan nan nan nan
6792 nan nan nan nan nan nan

In [90]:
# 0 0.39133535 18.75376741 -53.36032453 -26.42131618 785.1811367994083 1.5578904428966628e-12
# [np.float64(459.9999976194083), np.float64(231.9999983694081), np.float64(177.99999898940814)]

In [ ]:
# Leveraging Gradient Descent to find the best model parameters
m, n = X_train.shape
dj_dw, dj_db = np.zeros(n), 0
w, b = np.zeros(n), 0
learning_rate = 0.01
for iter in range(10000):

    w = w - learning_rate * dj_dw
    b = b - learning_rate * dj_db

    error_sqrd = 0
    dj_dw = np.zeros(n)
    dj_db = 0.
    for i in range(m):
        y_hat = np.dot(w, X_train[i]) + b
        error_sqrd += (y_hat - y_train[i])**2

        for j in range(n):
            dj_dw[j] += (y_hat - y_train[i]) * X_train[i, j]

        dj_db += (y_hat - y_train[i])


    cost = error_sqrd / (2 * m)
    dj_dw = dj_dw / m
    dj_db = dj_db / m

    print(iter, w, b, cost) 

predictions = []
for i in range(m):
    predictions.append((np.dot(w, X_train[i]) + b ))

print(predictions)

0 [0. 0. 0. 0.] 0.0 1.9519633853882916
1 [3.03741110e-02 2.11178489e-01 3.57704199e-05 1.34804045e-05] 0.01809211958904106 2.2069876189204
2 [ 2.31229525e-02 -2.86206252e-02  2.86676067e-05  9.22076788e-06] 0.013333730024965074 2.5338577293576336
3 [5.76563625e-02 2.37300796e-01 6.91901773e-05 2.47130499e-05] 0.03395207375032188 2.9508695825712494
4 [ 4.49394066e-02 -6.37896707e-02  5.58701831e-05  1.79201895e-05] 0.02587439321399749 3.4810319412686597
5 [8.48117321e-02 2.70946566e-01 1.02488892e-04 3.59798287e-05] 0.04973537738119464 4.153278831175517
6 [ 6.53305695e-02 -1.07216611e-01  8.14716494e-05  2.60392785e-05] 0.037549865617938175 5.003993831377833
7 [1.12021605e-01 3.14027130e-01 1.35872589e-04 4.73635239e-05] 0.06555221051552727 6.078926540858717
8 [ 8.41405060e-02 -1.61049987e-01  1.05293618e-04  3.35016000e-05] 0.0482654651366689 7.4356021206020895
9 [1.39507555e-01 3.68946307e-01 1.69593117e-04 5.89659792e-05] 0.08153715948810578 9.146350770141941
10 [ 1.01166782e-01 -2.27990397e-01  1.27104729e-04  4.02088499e-05] 0.05789826896285216 11.302116635834937
11 [1.67541879e-01 4.38727085e-01 2.03960149e-04 7.09130710e-05] 0.09785561559449098 14.017246683773047
12 [ 1.16148692e-01 -3.11432544e-01  1.46607236e-04  4.60352961e-05] 0.06628996533927042 17.435511663588162
13 [1.96460838e-01 5.27170905e-01 2.39356274e-04 8.33609568e-05] 0.1147118163891924 21.737676156729894
14 [ 1.28752460e-01 -4.15643846e-01  1.63420135e-04  5.08207851e-05] 0.07323786264756456 27.15101625925566
15 [2.26681300e-01 6.39057915e-01 2.76255964e-04 9.65039300e-05] 0.13235895235148953 33.961285988579846
16 [ 1.38552614e-01 -5.45988984e-01  1.77057941e-04  5.43619502e-05] 0.07848358185241017 42.52776242447248
17 [2.58721656e-01 7.80398759e-01 3.15249408e-04 1.10584293e-04] 0.15111187040519225 53.302161684353734
18 [ 1.45008577e-01 -7.09212229e-01  1.86904011e-04  5.64011533e-05] 0.08169883637683428 66.85242162531117
19 [2.93228112e-01 9.58751137e-01 3.57072476e-04 1.25904771e-04] 0.1713630425167914 83.89260338957509
20 [ 1.47435220e-01 -9.13792405e-01  1.92176979e-04  5.66125815e-05] 0.08246755016115294 105.3204860561742
21 [3.31007744e-01 1.18361781e+00 4.02644391e-04 1.42844110e-04] 0.19360263951486198 132.2648336895563
22 [ 1.44965839e-01 -1.17038917e+00  1.91888567e-04  5.45847642e-05] 0.08026337188769667 166.14482331009586
23 [3.73070051e-01 1.46694703e+00 4.53115081e-04 1.61876701e-04] 0.21844376642343702 208.7447625618327
24 [ 1.36505598e-01 -1.49240413e+00  1.84790525e-04  4.97985902e-05] 0.07442140098712235 262.3080308276436
25 [4.20679190e-01 1.82376166e+00 5.09924709e-04 1.83597233e-04] 0.24665418736331082 329.65518962158797
26 [ 1.20672993e-01 -1.89668631e+00  1.69307920e-04  4.15996679e-05] 0.06410263631954796 414.33248055677353
27 [4.75419648e-01 2.27295023e+00 5.74878515e-04 2.08751702e-04] 0.2791962097555729 520.7985290378002
28 [ 9.57262469e-02 -2.40441911e+00  1.43455254e-04  2.91635723e-05] 0.048249275301893824 654.6590832888453
29 [5.39278810e-01 2.83826149e+00 6.50240913e-04 2.38276390e-04] 0.31727682714999766 822.9621473017377
30 [ 5.94707649e-02 -3.04223549e+00  1.04730993e-04  1.14521492e-05] 0.025528509561046964 1034.5690459186205
31 [6.14750755e-01 3.54955479e+00 7.38853782e-04 2.73346871e-04] 0.3624107601143056 1300.620957952957
32 [ 9.14277664e-03 -3.84362004e+00  4.99849616e-05 -1.28414241e-05] -0.005738142429390969 1635.125479471472
33 [7.04966764e-01 4.44437227e+00 8.44285197e-04 3.15439623e-04] 0.41649971369476324 2055.694098729841
34 [-5.87369658e-02 -4.85067182e+00 -2.47483877e-05 -4.53617150e-05] -0.0476636867079438 2584.4694094797833
35 [8.13859394e-01 5.56991541e+00 9.71016413e-04 3.66409497e-04] 0.48193202374606087 3249.2908787458964
36 [-1.48547132e-01 -6.11632069e+00 -1.24459608e-04 -8.81778838e-05] -0.10290736749887347 4085.160544630526
37 [9.46368760e-01 6.98553024e+00 1.12467695e-03 4.28587104e-04] 0.5617079378794765 5136.085810477363
38 [-2.65797090e-01 -7.70711388e+00 -2.55427827e-04 -1.43892880e-04] -0.17481512516539333 6457.396355161985
39 [1.10870189e+00 8.76583187e+00 1.31234018e-03 5.04901267e-04] 0.6595971264080642 8118.657140632975
40 [-4.17417684e-01 -9.70671953e+00 -4.25552135e-04 -2.15780732e-04] -0.2675961937280801 10207.330881264355
41 [1.30865881e+00 1.10046329e+01 1.54289492e-03 5.99032974e-04] 0.7803367155316513 12833.38279738579
42 [-6.12126836e-01 -1.22203315e+01 -6.44768235e-04 -3.07959160e-04] -0.3865451359034765 16135.07008490786
43 [1.55604250e+00 1.38198826e+01 1.82751264e-03 7.15608933e-04] 0.9298802684396151 20286.220906112612
44 [-8.60889205e-01 -1.53802078e+01 -9.25572293e-04 -4.25606604e-04] -0.5383210058084501 25505.38612726759
45 [1.86317433e+00 1.73598768e+01 2.18023491e-03 8.60444930e-04] 1.11571082233734 32067.345625439542
46 [-1.17749412e+00 -1.93526333e+01 -1.28367957e-03 -5.75235084e-04] -0.7312983371313986 40317.57495068606
47 [2.24554212e+00 2.18110653e+01 2.61871190e-03 1.04085180e-03] 1.3472344618422536 50690.433987134136
48 [-1.57928220e+00 -2.43466745e+01 -1.73885251e-03 -7.65033270e-04] -0.9760084360402383 63732.035212948664
49 [2.72261492e+00 2.74078686e+01 3.16513098e-03 1.26602009e-03] 1.6362751493009142 80128.99553158483
50 [-2.08805892e+00 -3.06251863e+01 -2.31594189e-03 -1.00529781e-03] -1.2856942124658115 100744.58540605502
51 [3.31886738e+00 3.44450193e+01 3.84738412e-03 1.54750376e-03] 1.9976968635830294 126664.17848255095
52 [-2.73124325e+00 -3.85186510e+01 -3.04619583e-03 -1.30897565e-03] -1.677007760978102 159252.39454361086
53 [4.06506774e+00 4.32930797e+01 4.70053572e-03 1.89982822e-03] 2.450185801479494 200224.94426364405
54 [-3.54331177e+00 -4.84425772e+01 -3.96890560e-03 -1.69234584e-03] -2.170887417968452 251738.95826279945
55 [4.99989713e+00 5.44179508e+01 5.76866806e-03 2.34125491e-03] 3.0172338228478384 316506.5561199822
56 [-4.56761439e+00 -6.09193758e+01 -5.13347484e-03 -2.17587683e-03] -2.793660470942506 397937.63454742904
57 [6.17198551e+00 6.84054019e+01 7.10720151e-03 2.89474250e-03] 3.7283749157772603 500319.3922651566
58 [-5.85865718e+00 -7.66058637e+01 -6.60202123e-03 -2.78530426e-03] -3.5784295758926077 629042.0432341745
59 [7.64247139e+00 8.59919098e+01 8.78581171e-03 3.58915548e-03] 4.62073977909936 790882.6016405371
60 [-7.48497255e+00 -9.63278440e+01 -8.45264741e-03 -3.55298609e-03] -4.566815875424004 994361.6793947675
61 [9.48822017e+00 1.08103433e+02 1.08920973e-02 4.46078360e-03] 5.7410103678829465 1250192.0808875207
62 [-9.53272787e+00 -1.21123583e+02 -1.07835535e-02 -4.51960635e-03] -5.811150589947177 1571842.8127012812
63 [1.18058704e+01 1.35904163e+02 1.35361914e-02 5.55525232e-03] 7.147877304884599 1976248.2023660536
64 [-1.21102625e+01 -1.52298474e+02 -1.37182079e-02 -5.73631727e-03] -7.377230465532421 2484699.459974713
65 [1.47169213e+01 1.70857814e+02 1.68565589e-02 6.92992473e-03] 8.915129535916059 3123965.6217592116
66 [-1.53537922e+01 -1.91493761e+02 -1.74118479e-02 -7.26743252e-03] -9.347782148043624 3927702.89127295
67 [1.83741287e+01 2.14804689e+02 2.10272866e-02 8.65692140e-03] 11.135538893594749 4938226.577434782
68 [-1.94345812e+01 -2.40772950e+02 -2.20596533e-02 -9.19381337e-03] -11.826817876842643 6208738.918757983
69 [2.29695472e+01 2.70058564e+02 2.62672474e-02 1.08269173e-02] 13.9257440844341 7806130.084666495
70 [-2.45679590e+01 -3.02730448e+02 -2.79070230e-02 -1.16171260e-02] -14.945111817703136 9814499.821535217
71 [2.87446407e+01 3.39528509e+02 3.28516233e-02 1.35539155e-02] 17.432391232065342 12339585.151728388
72 [-3.10246581e+01 -3.80628153e+02 -3.52624949e-02 -1.46651943e-02] -18.86708535418812 15514327.23595542
73 [3.60029952e+01 4.26872039e+02 4.11263929e-02 1.69812492e-02] 21.839854264790347 19505870.484144956
74 [-3.91450676e+01 -4.78567189e+02 -4.45139907e-02 -1.84987296e-02] -23.799463835842893 24524362.40532527
75 [4.51263007e+01 5.36687684e+02 5.15265459e-02 2.12891273e-02] 27.37994161161017 30834017.49263797
76 [-4.93571546e+01 -6.01703819e+02 -5.61492394e-02 -2.33197921e-02] -30.002160545529428 38767027.63695576
77 [5.65944472e+01 6.74757086e+02 6.45989839e-02 2.67041227e-02] 34.3441002464186 48741051.427135095
78 [-6.21989962e+01 -7.56520916e+02 -7.07814561e-02 -2.93824289e-02] -37.801960907280666 61281203.116830416
79 [7.10107886e+01 8.48349393e+02 8.10313139e-02 3.35111003e-02] 43.098759600904835 77047698.93707116
80 [-7.83471090e+01 -9.51169274e+02 -8.91816270e-02 -3.70060494e-02] -47.60972738360609 96870616.28278616
81 [8.91339084e+01 1.06660397e+03 1.01688048e-01 4.20682146e-02] 54.10462317511023 121793595.781376
82 [-9.86520665e+01 -1.19589673e+03 -1.12319101e-01 -4.65922419e-02] -59.942030869109665 153128787.07794487
83 [1.11917557e+02 1.34101157e+03 1.27656121e-01 5.28257658e-02] 67.94092351370432 192525931.1330588
84 [-1.24183281e+02 -1.50358770e+03 -1.41412623e-01 -5.86459163e-02] -75.44834743424721 242059216.09069204
85 [1.40560866e+02 1.68601929e+03 1.60302109e-01 6.63499071e-02] 85.33591752825353 304336479.52013963
86 [-1.56285305e+02 -1.89044152e+03 -1.77994503e-01 -7.38018870e-02] -94.94525227865407 382636506.3318334
87 [1.76571477e+02 2.11979122e+03 2.01344184e-01 8.33524515e-02] 107.20522768865436 481081650.85314685
88 [-1.96648623e+02 -2.37682529e+03 -2.23991284e-01 -9.28582950e-02] -119.45941114383075 604854871.3032308
89 [2.21844919e+02 2.66516468e+03 2.52942567e-01 1.04728348e-01] 134.7000476776898 760472603.1382065
90 [-2.47398650e+02 -2.98834620e+03 -2.81825178e-01 -1.16818628e-01] -150.28163260525636 956127837.5530868
91 [2.78764402e+02 3.35085265e+03 3.17813263e-01 1.31602797e-01] 169.26775044873185 1202121467.6011052
92 [-3.11207632e+02 -3.75719967e+03 -3.54541585e-01 -1.46944554e-01] -189.03482699922304 1511404611.5207937
93 [3.50326288e+02 4.21295538e+03 3.99371050e-01 1.65390492e-01] 212.72808959068547 1900260465.6099694
94 [-3.91435334e+02 -4.72386442e+03 -4.45969433e-01 -1.84822344e-01] -237.759449898749 2389161584.9630966
95 [4.40297849e+02 5.29686107e+03 5.01909262e-01 2.07870101e-01] 267.36900586355 3003847726.3472276
96 [-4.92305930e+02 -5.93923354e+03 -5.60922761e-01 -2.32446386e-01] -299.0209285827118 3776680999.687991
97 [5.53415598e+02 6.65963540e+03 6.30825825e-01 2.61277907e-01] 336.0670829446916 4748349674.432534
98 [-6.19130393e+02 -7.46729399e+03 -7.05454174e-01 -2.92324189e-01] -376.04472730703765 5970010343.10233
99 [6.95634665e+02 8.37302602e+03 7.92907450e-01 3.28425546e-01] 422.4389941620901 7505981223.059832
100 [-7.78586110e+02 -9.38849534e+03 -8.87173496e-01 -3.67608396e-01] -472.88616231957394 9437128393.940348
101 [8.74442320e+02 1.05272399e+04 9.96686934e-01 4.12848037e-01] 531.0319136100915 11865123250.003332
102 [-9.79068439e+02 -1.18039853e+04 -1.11564842e+00 -4.62262768e-01] -594.6439070711814 14917795314.546196
103 [1.09925216e+03 1.32356924e+04 1.25289241e+00 5.18989888e-01] 667.5629164472313 18755862232.344696
104 [-1.23113270e+03 -1.48409351e+04 -1.40290822e+00 -5.81270864e-01] -747.7284282850961 23581391262.010246
105 [1.38189974e+03 1.66409788e+04 1.57501213e+00 6.52439098e-01] 839.2199723672292 29648437750.48008
106 [-1.54804991e+03 -1.86592344e+04 -1.76407710e+00 -7.30898422e-01] -940.1994855567763 37276420686.02318
107 [1.73726565e+03 2.09223812e+04 1.98000465e+00 8.20221350e-01] 1055.0403790030277 46866939528.34833
108 [-1.94650545e+03 -2.34599099e+04 -2.21817039e+00 -9.19023234e-01] -1182.1904632257415 58924917691.4116
109 [2.18405898e+03 2.63053077e+04 2.48919163e+00 1.03116990e+00] 1326.386559095803 74085185844.91852
110 [-2.44747756e+03 -2.94957084e+04 -2.78909577e+00 -1.15554990e+00] -1486.441874822753 93145904597.11151
111 [2.74580234e+03 3.30731597e+04 3.12938037e+00 1.29639064e+00] 1667.5442712863355 117110586202.43881
112 [-3.07734177e+03 -3.70844036e+04 -3.50691186e+00 -1.45293130e+00] -1868.9721281332895 147240927660.76917
113 [3.45207024e+03 4.15822523e+04 3.93427520e+00 1.62984680e+00] 2096.474729241208 185123236774.9345
114 [-3.86925955e+03 -4.66255266e+04 -4.40941082e+00 -1.82682417e+00] -2349.920865441279 232751948378.0132
115 [4.34004615e+03 5.22805738e+04 4.94625193e+00 2.04909406e+00] 2635.7602268209116 292634627708.1658
116 [-4.86492416e+03 -5.86214002e+04 -5.54410803e+00 -2.29691347e+00] -2954.6092792861186 367923989168.15857
117 [5.45648014e+03 6.57313716e+04 6.21858886e+00 2.57620488e+00] 3313.7930547389074 462583881017.7041
118 [-6.11675579e+03 -7.37035853e+04 -6.97074367e+00 -2.88794870e+00] -3714.8732274343006 581597974791.4886
119 [6.86015021e+03 8.26428055e+04 7.81827180e+00 3.23893053e+00] 4166.270303016216 731232146562.0167
120 [-7.69066132e+03 -9.26661315e+04 -8.76442793e+00 -3.63104696e+00] -4670.7393331493895 919364363944.6959
121 [8.62495681e+03 1.03905232e+05 9.82952074e+00 4.07216214e+00] 5238.073247867922 1155899446797.3237
122 [-9.66950427e+03 -1.16507382e+05 -1.10195954e+01 -4.56533118e+00] -5872.5323143986825 1453290538012.1035
123 [1.08438136e+04 1.30638080e+05 1.23582239e+01 5.11976770e+00] 6585.6302693311645 1827194738891.3892
124 [-1.21574673e+04 -1.46482537e+05 -1.38549771e+01 -5.73998988e+00] -7383.5244890547965 2297297427119.5757
125 [1.36335391e+04 1.64248784e+05 1.55375124e+01 6.43690158e+00] 8279.887702959499 2888348656176.781
126 [-1.52855375e+04 -1.84169732e+05 -1.74198510e+01 -7.21686686e+00] -9283.26694773433 3631466200742.863
127 [1.71410071e+04 2.06506887e+05 1.95347698e+01 8.09290834e+00] 10410.045035533833 4565773851067.461
128 [-1.92184021e+04 -2.31553130e+05 -2.19019017e+01 -9.07371716e+00] -11671.777774477468 5740461209532.0625
129 [2.15508793e+04 2.59637203e+05 2.45604438e+01 1.01749736e+01] 13088.251096067037 7217373433955.493
130 [-2.41631196e+04 -2.91127382e+05 -2.75371015e+01 -1.14083007e+01] -14674.807817488821 9074267272927.426
131 [2.70953271e+04 3.26436945e+05 3.08791269e+01 1.27927141e+01] 16455.50848803649 11408904817523.477
132 [-3.03800206e+04 -3.66028963e+05 -3.46221336e+01 -1.43435293e+01] -18450.461243212674 14344200498000.281
133 [3.40662556e+04 4.10422998e+05 3.88234858e+01 1.60839491e+01] 20689.097120486316 18034692305504.934
134 [-3.81964138e+04 -4.60201306e+05 -4.35300127e+01 -1.80339375e+01] -23197.519433902424 22674677936883.5
135 [4.28306713e+04 5.16017077e+05 4.88117761e+01 2.02219560e+01] 26011.907673441478 28508444215843.496
136 [-4.80238183e+04 -5.78602413e+05 -5.47297226e+01 -2.26738187e+01] -29165.90646678429 35843128350936.57
137 [5.38500045e+04 6.48778518e+05 6.13698630e+01 2.54245930e+01] 32704.176387652587 45064888152251.95
138 [-6.03796294e+04 -7.27465888e+05 -6.88109083e+01 -2.85074545e+01] -36669.84716330538 56659232539392.484
139 [6.77044030e+04 8.15696969e+05 7.71589064e+01 3.19657697e+01] 41118.23899405414 71236582705076.77
140 [-7.59143582e+04 -9.14629124e+05 -8.65149189e+01 -3.58419752e+01] -46104.41045588065 89564409683260.39
141 [8.51232756e+04 1.02556039e+06 9.70101707e+01 4.01898667e+01] 51697.08055055157 112607640306406.25
142 [-9.54458801e+04 -1.14994592e+06 -1.08773839e+02 -4.50635303e+01] -57966.30905037757 141579458852246.7
143 [1.07023694e+05 1.28941769e+06 1.21968788e+02 5.05298679e+01] 64997.65780138327 178005178994545.66
144 [-1.20002495e+05 -1.44580529e+06 -1.36759560e+02 -5.66576179e+01] -72880.05044882718 223802548800161.06
145 [1.34558676e+05 1.62116050e+06 1.53348785e+02 6.35301554e+01] 81720.22193895612 281382716684793.47
146 [-1.50877063e+05 -1.81778368e+06 -1.71945481e+02 -7.12346460e+01] -91630.8161362531 353777174001770.6
147 [1.69177887e+05 2.03825447e+06 1.92802260e+02 7.98751705e+01] 102745.1855583521 444797357560812.4
148 [-1.89695075e+05 -2.28546509e+06 -2.16184076e+02 -8.95620687e+01] -115205.7999611372 559235314859779.0
149 [2.12703967e+05 2.56265883e+06 2.42406368e+02 1.00425449e+02] 129179.47478277303 703115996689700.0
150 [-2.38500230e+05 -2.87347209e+06 -2.71804427e+02 -1.12604792e+02] -144846.18210025094 884014459860973.4
151 [2.67428483e+05 3.22198254e+06 3.04772673e+02 1.26262924e+02] 162414.80691519912 1111454680198632.4
152 [-2.99862030e+05 -3.61276217e+06 -3.41734846e+02 -1.41575973e+02] -182112.47494277274 1397410972587171.5
153 [3.36232584e+05 4.05093777e+06 3.83184649e+02 1.58747894e+02] 204200.9618288851 1756938416920462.0
154 [-3.77011062e+05 -4.54225764e+06 -4.29657043e+02 -1.78000892e+02] -228966.68123593254 2208965480738998.2
155 [4.22738678e+05 5.09316753e+06 4.81770543e+02 1.99590632e+02] 256737.9047024347 2777290568698027.0
156 [-4.74009083e+05 -5.71089472e+06 -5.40199961e+02 -2.23797255e+02] -287875.58996943815 3491834965387746.5
157 [5.31501156e+05 6.40354331e+06 6.05720724e+02 2.50941434e+02] 322791.6101942952 4390218136671392.0
158 [-5.95962864e+05 -7.18020005e+06 -6.79183485e+02 -2.81376159e+02] -361940.64833959995 5519738326298099.0
159 [6.68246164e+05 8.05105403e+06 7.61560943e+02 3.15503826e+02] 405839.6859892772 6939862722608194.0
160 [-7.49293050e+05 -9.02752988e+06 -8.53924846e+02 -3.53769027e+02] -455061.2473163471 8725358298089322.0
161 [8.40173079e+05 1.01224381e+07 9.57495905e+02 3.96676902e+02] 510254.46253257606 1.09702281548048e+16
162 [-9.42072196e+05 -1.13501428e+07 -1.07362386e+03 -4.44787212e+02] -572140.0175019648 1.3792660617137624e+16
163 [1.05633354e+06 1.27267502e+07 1.20384123e+03 4.98734277e+02] 641533.188293548 1.7341251632603156e+16
164 [-1.18444978e+06 -1.42703201e+07 -1.34984728e+03 -5.59222659e+02] -719340.943735991 2.1802828078841612e+16
165 [1.32810800e+06 1.60011026e+07 1.51356655e+03 6.27049085e+02] 806587.4499221618 2.741228385970697e+16
166 [-1.48918653e+06 -1.79418039e+07 -1.69713777e+03 -7.03100184e+02] -904413.8877118345 3.4464946643062948e+16
167 [1.66980490e+06 2.01178841e+07 1.90297834e+03 7.88376869e+02] 1014107.0547442246 4.333212632659035e+16
168 [-1.87232629e+06 -2.25578911e+07 -2.13377955e+03 -8.83994679e+02] -1137102.604131966 5.448066383011536e+16
169 [2.09941396e+06 2.52938356e+07 2.39257844e+03 9.91211243e+02] 1275017.533348335 6.849750942290315e+16
170 [-2.35404068e+06 -2.83616103e+07 -2.68276100e+03 -1.11142991e+03] -1429657.731711933 8.612062459024554e+16
171 [2.63955330e+06 3.18014616e+07 3.00814338e+03 1.24623107e+03] 1603055.3489457467 1.0827783436654454e+17
172 [-2.95969108e+06 -3.56585169e+07 -3.37298502e+03 -1.39737993e+03] -1797481.7670785752 1.3613567563973422e+17
173 [3.31866030e+06 3.99833769e+07 3.78208155e+03 1.56686268e+03] 2015491.0972319231 1.7116081320160976e+17
174 [-3.72116388e+06 -4.48327796e+07 -4.24079064e+03 -1.75689949e+03] -2259939.9782679523 2.1519725698768506e+17
175 [4.17248870e+06 5.02703445e+07 4.75513939e+03 1.96998674e+03] 2534038.7719104323 2.7056344585413834e+17
176 [-4.67854925e+06 -5.63674069e+07 -5.33186625e+03 -2.20891665e+03] -2841379.9509468772 3.401743091765079e+17
177 [5.24599101e+06 6.32039544e+07 5.97854663e+03 2.47682701e+03] 3185998.9670589003 4.2769473259185056e+17
178 [-5.88225180e+06 -7.08696758e+07 -6.70365500e+03 -2.77722927e+03] -3572413.444617012 5.3773250757716294e+17
179 [6.59568519e+06 7.94651379e+07 7.51671344e+03 3.11406771e+03] 4005696.203866958 6.760809233093029e+17
180 [-7.39564427e+06 -8.91031046e+07 -8.42837909e+03 -3.49175800e+03] -4491528.046204034 8.500237728275572e+17
181 [8.29263019e+06 9.99100167e+07 9.45062152e+03 3.91525840e+03] 5036286.054391213 1.0687188315198627e+18
182 [-9.29840403e+06 -1.12027650e+08 -1.05968421e+04 -4.39012148e+03] -5647113.471669158 1.3436799973791946e+18
183 [1.04261671e+07 1.25614977e+08 1.18820876e+04 4.92258032e+03] 6332027.204113178 1.689383476839574e+18
184 [-1.16907079e+07 -1.40850248e+08 -1.33232097e+04 -5.51961690e+03] -7100009.196746077 2.124029930776089e+18
185 [1.31086227e+07 1.57933337e+08 1.49391240e+04 6.18906713e+03] 7961138.073271178 2.6705027062728515e+18
186 [-1.46985064e+07 -1.77088356e+08 -1.67510201e+04 -6.93971017e+03] -8926707.544938002 3.357572603322416e+18
187 [1.64812235e+07 1.98566601e+08 1.87826780e+04 7.78139708e+03] 10009388.392896075 4.2214126052375685e+18
188 [-1.84801547e+07 -2.22649845e+08 -2.10607415e+04 -8.72516660e+03] -11223380.869546056 5.307502320582733e+18
189 [2.07215307e+07 2.49654036e+08 2.36151060e+04 9.78340344e+03] 12584614.825510483 6.673022402036803e+18

C:\Users\alirm\AppData\Local\Temp\ipykernel_55216\3740082756.py:17: RuntimeWarning: overflow encountered in scalar add
  error_sqrd += (y_hat - y_train[i])**2
C:\Users\alirm\AppData\Local\Temp\ipykernel_55216\3740082756.py:17: RuntimeWarning: overflow encountered in scalar power
  error_sqrd += (y_hat - y_train[i])**2

3095 [6.18991428e+151 7.45763992e+152 7.05428002e+148 2.92248817e+148] 3.759263181227351e+151 inf
3096 [-6.94066095e+151 -8.36214329e+152 -7.90986170e+148 -3.27694353e+148] -4.215207188823595e+151 inf
3097 [7.78246228e+151 9.37634978e+152 8.86921301e+148 3.67438917e+148] 4.7264505803792284e+151 inf
3098 [-8.72636189e+151 -1.05135648e+153 -9.94491969e+148 -4.12003920e+148] -5.299700367753822e+151 inf
3099 [9.78474281e+151 1.17887075e+153 1.11510940e+149 4.61974009e+148] 5.942477025903199e+151 inf
3100 [-1.09714900e+152 -1.32185064e+153 -1.25035597e+149 -5.18004745e+148] -6.663213154134088e+151 inf
3101 [1.23021723e+152 1.48217192e+153 1.40200598e+149 5.80831195e+148] 7.471364103537045e+151 inf
3102 [-1.37942471e+152 -1.66193784e+153 -1.57204893e+149 -6.51277580e+148] -8.377532021917478e+151 inf
3103 [1.54672888e+152 1.86350675e+153 1.76271563e+149 7.30268088e+148] 9.393604943577808e+151 inf
3104 [-1.73432462e+152 -2.08952305e+153 -1.97650743e+149 -8.18838998e+148] -1.0532912748665234e+152 inf
3105 [1.94467300e+152 2.34295184e+153 2.21622906e+149 9.18152272e+148] 1.1810402038127904e+152 inf
3106 [-2.18053359e+152 -2.62711785e+153 -2.48502545e+149 -1.02951080e+149] -1.324283221845591e+152 inf
3107 [2.44500063e+152 2.94574908e+153 2.78642293e+149 1.15437551e+149] 1.4848995368660578e+152 inf
3108 [-2.74154368e+152 -3.30302565e+153 -3.12437555e+149 -1.29438448e+149] -1.6649962773915303e+152 inf
3109 [3.07405310e+152 3.70363467e+153 3.50331691e+149 1.45137452e+149] 1.86693613601537e+152 inf
3110 [-3.44689108e+152 -4.15283175e+153 -3.92821836e+149 -1.62740516e+149] -2.0933683656160597e+152 inf
3111 [3.86494889e+152 4.65650990e+153 4.40465417e+149 1.82478576e+149] 2.3472635349568275e+152 inf
3112 [-4.33371104e+152 -5.22127690e+153 -4.93887473e+149 -2.04610576e+149] -2.6319524996340437e+152 inf
3113 [4.85932723e+152 5.85454194e+153 5.53788848e+149 2.29426866e+149] 2.951170099635735e+152 inf
3114 [-5.44869302e+152 -6.56461281e+153 -6.20955390e+149 -2.57253012e+149] -3.3091041567790706e+152 inf
3115 [6.10954032e+152 7.36080498e+153 6.96268257e+149 2.88454065e+149] 3.7104504148249277e+152 inf
3116 [-6.85053880e+152 -8.25356368e+153 -7.80715481e+149 -3.23439352e+149] -4.160474143030707e+152 inf
3117 [7.68140963e+152 9.25460104e+153 8.75404926e+149 3.62667847e+149] 4.665079211318204e+152 inf
3118 [-8.61305302e+152 -1.03770497e+154 -9.81578826e+149 -4.06654187e+149] -5.230885543256941e+152 inf
3119 [9.65769122e+152 1.16356351e+154 1.10063008e+150 4.55975432e+149] 5.865315962967809e+152 inf
3120 [-1.08290289e+153 -1.30468685e+154 -1.23412051e+150 -5.11278628e+149] -6.576693575295808e+152 inf
3121 [1.21424327e+153 1.46292641e+154 1.38380140e+150 5.73289297e+149] 7.374350956781296e+152 inf
3122 [-1.36151334e+153 -1.64035813e+154 -1.55163641e+150 -6.42820960e+149] -8.268752589911627e+152 inf
3123 [1.52664513e+153 1.83930974e+154 1.73982736e+150 7.20785803e+149] 9.271632146866442e+152 inf
3124 [-1.71180500e+153 -2.06239129e+154 -1.95084314e+150 -8.08206649e+149] -1.0396146423789453e+153 inf
3125 [1.91942208e+153 2.31252939e+154 2.18745207e+150 9.06230374e+149] 1.1657047945047533e+153 inf
3126 [-2.15222009e+153 -2.59300561e+154 -2.45275823e+150 -1.01614295e+150] -1.3070878501883635e+153 inf
3127 [2.41325312e+153 2.90749952e+154 2.75024217e+150 1.13938633e+150] 1.4656186164489457e+153 inf
3128 [-2.70594566e+153 -3.26013697e+154 -3.08380659e+150 -1.27757734e+150] -1.6433768614498553e+153 inf
3129 [3.03413756e+153 3.65554422e+154 3.45782752e+150 1.43252891e+150] 1.842694599016634e+153 inf
3130 [-3.40213436e+153 -4.09890863e+154 -3.87721177e+150 -1.60627385e+150] -2.0661866823714953e+153 inf
3131 [3.81476383e+153 4.59604669e+154 4.34746122e+150 1.80109153e+150] 2.3167851084425327e+153 inf
3132 [-4.27743926e+153 -5.15348038e+154 -4.87474511e+150 -2.01953777e+150] -2.5977774827880384e+153 inf
3133 [4.79623050e+153 5.77852268e+154 5.46598087e+150 2.26447836e+150] 2.9128501497565186e+153 inf
3134 [-5.37794358e+153 -6.47937353e+154 -6.12892493e+150 -2.53912668e+150] -3.2661365537091473e+153 inf
3135 [6.03021000e+153 7.26522740e+154 6.87227448e+150 2.84708586e+150] 3.662271465755557e+153 inf
3136 [-6.76158686e+153 -8.14639393e+154 -7.70578154e+150 -3.19239601e+150] -4.1064517874048994e+153 inf
3137 [7.58166912e+153 9.13443316e+154 8.64038088e+150 3.57958727e+150] 4.604504728816367e+153 inf
3138 [-8.50121543e+153 -1.02423072e+155 -9.68833355e+150 -4.01373920e+150] -5.162964256081295e+153 inf
3139 [9.53228935e+153 1.14845503e+155 1.08633877e+151 4.50054745e+150] 5.789156810449135e+153 inf
3140 [-1.06884176e+154 -1.28774593e+155 -1.21809587e+151 -5.04639847e+150] -6.491297424051443e+153 inf
3141 [1.19847673e+154 1.44393081e+155 1.36583321e+151 5.65845329e+150] 7.278597493065162e+153 inf
3142 [-1.34383455e+154 -1.61905864e+155 -1.53148893e+151 -6.34474146e+150] -8.161385622196612e+153 inf
3143 [1.50682215e+154 1.81542693e+155 1.71723629e+151 7.11426642e+150] 9.15124312584385e+153 inf
3144 [-1.68957779e+154 -2.03561184e+155 -1.92551210e+151 -7.97712358e+150] -1.0261155963583199e+154 inf
3145 [1.89449903e+154 2.28250198e+155 2.15904875e+151 8.94463277e+150] 1.1505685103221341e+154 inf
3146 [-2.12427424e+154 -2.55933631e+155 -2.42090999e+151 -1.00294868e+151] -1.2901157546411872e+154 inf
3147 [2.38191784e+154 2.86974662e+155 2.71453120e+151 1.12459178e+151] 1.446588052290245e+154 inf
3148 [-2.67080987e+154 -3.21780519e+155 -3.04376440e+151 -1.26098843e+151] -1.622038166343386e+154 inf
3149 [2.99474030e+154 3.60807821e+155 3.41292880e+151 1.41392800e+151] 1.8187678302120437e+154 inf
3150 [-3.35795879e+154 -4.04568568e+155 -3.82686748e+151 -1.58541693e+151] -2.0393579441298945e+154 inf
3151 [3.76523041e+154 4.53636857e+155 4.29101090e+151 1.77770497e+151] 2.2867024340323412e+154 inf
3152 [-4.22189815e+154 -5.08656417e+155 -4.81144818e+151 -1.99331475e+151] -2.5640462170266818e+154 inf
3153 [4.73395306e+154 5.70349051e+155 5.39500695e+151 2.23507487e+151] 2.875027771521472e+154 inf
3154 [-5.30811279e+154 -6.39524104e+155 -6.04934291e+151 -2.50615698e+151] -3.2237268704949233e+154 inf
3155 [5.95190976e+154 7.17089087e+155 6.78304031e+151 2.81011741e+151] 3.6147181041146155e+154 inf
3156 [-6.67378994e+154 -8.04061575e+155 -7.60572456e+151 -3.15094383e+151] -4.0531308938737877e+154 inf
3157 [7.48322370e+154 9.01582562e+155 8.52818845e+151 3.53310753e+151] 4.54471678557015e+154 inf
3158 [-8.39083001e+154 -1.01093143e+156 -9.56253380e+151 -3.96162215e+151] -5.0959249039457635e+154 inf
3159 [9.40851578e+154 1.13354272e+156 1.07223302e+152 4.44210936e+151] 5.7139865588778e+154 inf
3160 [-1.05496321e+155 -1.27102499e+156 -1.20227931e+152 -4.98087268e+151] -6.407010113072141e+154 inf
3161 [1.18291492e+155 1.42518185e+156 1.34809832e+152 5.58498018e+151] 7.184087355828545e+154 inf
3162 [-1.32638531e+155 -1.59803571e+156 -1.51160306e+152 -6.26235713e+151] -8.05541277839942e+154 inf
3163 [1.48725658e+155 1.79185422e+156 1.69493855e+152 7.02189007e+151] 9.032417315715831e+154 inf
3164 [-1.66763919e+155 -2.00918010e+156 -1.90050998e+152 -7.87354332e+151] -1.012791830904206e+155 inf
3165 [1.86989960e+155 2.25286446e+156 2.13101423e+152 8.82848973e+151] 1.135628765692167e+155 inf
3166 [-2.09669125e+155 -2.52610419e+156 -2.38947529e+152 -9.89925727e+151] -1.2733640360390145e+155 inf
3167 [2.35098944e+155 2.83248393e+156 2.67928393e+152 1.10998934e+152] 1.4278045935982257e+155 inf
3168 [-2.63613030e+155 -3.17602307e+156 -3.00424214e+152 -1.24461492e+152] -1.6009765470066595e+155 inf
3169 [2.95585461e+155 3.56122853e+156 3.36861307e+152 1.39556862e+152] 1.7951517424425627e+155 inf
3170 [-3.31435683e+155 -3.99315381e+156 -3.77717689e+152 -1.56483082e+152] -2.012877568019227e+155 inf
3171 [3.71634016e+155 4.47746535e+156 4.23529357e+152 1.75462207e+152] 2.257010373018437e+155 inf
3172 [-4.16707823e+155 -5.02051685e+156 -4.74897315e+152 -1.96743223e+152] -2.5307529403915283e+155 inf
3173 [4.67248428e+155 5.62943261e+156 5.32495460e+152 2.20605318e+152] 2.837696504130369e+155 inf
3174 [-5.23918874e+155 -6.31220099e+156 -5.97079423e+152 -2.47361537e+152] -3.1818678627349268e+155 inf
3175 [5.87462621e+155 7.07777927e+156 6.69496482e+152 2.77362898e+152] 3.5677822068600593e+155 inf
3176 [-6.58713302e+155 -7.93621106e+156 -7.50696679e+152 -3.11002988e+152] -4.000502354188331e+155 inf
3177 [7.38605656e+155 8.89875816e+156 8.41745279e+152 3.48723132e+152] 4.4857051686322275e+155 inf
3178 [-8.28187791e+155 -9.97804824e+156 -9.43836752e+152 -3.91018182e+152] -5.029756035220943e+155 inf
3179 [9.28634938e+155 1.11882405e+157 1.05831044e+153 4.38443006e+152] 5.639792367708021e+155 inf
3180 [-1.04126486e+156 -1.25452116e+157 -1.18666812e+153 -4.91619773e+152] -6.32381724444054e+155 inf
3181 [1.16755516e+156 1.40667635e+157 1.33059372e+153 5.51246109e+152] 7.090804400895668e+155 inf
3182 [-1.30916264e+156 -1.57728575e+157 -1.49197541e+153 -6.18104253e+152] -7.950815956290526e+155 inf
3183 [1.46794505e+156 1.76858760e+157 1.67293035e+153 6.93071319e+152] 8.915134418715231e+155 inf
3184 [-1.64598546e+156 -1.98309158e+157 -1.87583249e+153 -7.77130801e+152] -9.996410700574722e+155 inf
3185 [1.84561958e+156 2.22361177e+157 2.10334372e+153 8.71385476e+152] 1.1208830086149641e+156 inf
3186 [-2.06946642e+156 -2.49330358e+157 -2.35844876e+153 -9.77071875e+152] -1.256829832861422e+156 inf
3187 [2.32046263e+156 2.79570508e+157 2.64449433e+153 1.09557650e+153] 1.4092650317916086e+156 inf
3188 [-2.60190104e+156 -3.13478348e+157 -2.96523307e+153 -1.22845401e+153] -1.5801884057040964e+156 inf
3189 [2.91747383e+156 3.51498718e+157 3.32487276e+153 1.37744763e+153] 1.7718423016195836e+156 inf
3190 [-3.27132102e+156 -3.94130405e+157 -3.72813152e+153 -1.54451202e+153] -1.98674103067459e+156 inf
3191 [3.66808473e+156 4.41932698e+157 4.18029971e+153 1.73183889e+153] 2.227703853417424e+156 inf
3192 [-4.11297012e+156 -4.95532713e+157 -4.68730933e+153 -1.94188578e+153] -2.497891965741372e+156 inf
3193 [4.61181364e+156 5.55633632e+157 5.25581186e+153 2.17740832e+153] 2.8008499706743673e+156 inf
3194 [-5.17115963e+156 -6.23023919e+157 -5.89326547e+153 -2.44149631e+153] -3.140552380093884e+156 inf
3195 [5.79834617e+156 6.98587669e+157 6.60803296e+153 2.73761434e+153] 3.521455756424839e+156 inf
3196 [-6.50160132e+156 -7.83316204e+157 -7.40949135e+153 -3.06964719e+153] -3.948557178367027e+156 inf
3197 [7.29015110e+156 8.78321079e+157 8.30815500e+153 3.44195080e+153] 4.427459797667007e+156 inf
3198 [-8.17434051e+156 -9.84848665e+157 -9.31581350e+153 -3.85940942e+153] -4.964446346972789e+156 inf
3199 [9.16576926e+156 1.10429650e+158 1.04456863e+154 4.32749971e+153] 5.5665615631244074e+156 inf
3200 [-1.02774439e+157 -1.23823162e+158 -1.17125963e+154 -4.85236256e+153] -6.241704607191182e+156 inf
3201 [1.15239485e+157 1.38841113e+158 1.31331641e+154 5.44088364e+153] 6.998732693717988e+156 inf
3202 [-1.29216361e+157 -1.55680523e+158 -1.47260261e+154 -6.10078378e+153] -7.847577288691659e+156 inf
3203 [1.44888428e+157 1.74562308e+158 1.65120791e+154 6.84072021e+153] 8.799374400635169e+156 inf
3204 [-1.62461289e+157 -1.95734180e+158 -1.85147544e+154 -7.67040019e+153] -9.8666106741156e+156 inf
3205 [1.82165483e+157 2.19473892e+158 2.07603251e+154 8.60070829e+153] 1.1063287202275016e+157 inf
3206 [-2.04259510e+157 -2.46092887e+158 -2.32782510e+154 -9.64384926e+153] -1.2405103207438618e+157 inf
3207 [2.29033221e+157 2.75940379e+158 2.61015646e+154 1.08135081e+154] 1.390966199951519e+157 inf
3208 [-2.56811623e+157 -3.09407938e+158 -2.92673052e+154 -1.21250295e+154] -1.559670191415538e+157 inf
3209 [2.87959142e+157 3.46934625e+158 3.28170041e+154 1.35956194e+154] 1.748835526035789e+157 inf
3210 [-3.22884402e+157 -3.89012755e+158 -3.67972299e+154 -1.52445705e+154] -1.960943867465392e+157 inf
3211 [3.62045589e+157 4.36194350e+158 4.12601993e+154 1.70935154e+154] 2.198777869103837e+157 inf
3212 [-4.05956459e+157 -4.89098388e+158 -4.62644620e+154 -1.91667105e+154] -2.4654576797804452e+157 inf
3213 [4.55193079e+157 5.48418916e+158 5.18756691e+154 2.14913540e+154] 2.764481877046403e+157 inf
3214 [-5.10401387e+157 -6.14934163e+158 -5.81674341e+154 -2.40979430e+154] -3.0997733650811196e+157 inf
3215 [5.72305660e+157 6.89516743e+158 6.52222987e+154 2.70206734e+154] 3.475730839347085e+157 inf
3216 [-6.41718021e+157 -7.73145106e+158 -7.31328160e+154 -3.02978886e+154] -3.897286493160225e+157 inf
3217 [7.19549094e+157 8.66916375e+158 8.20027641e+154 3.39725823e+154] 4.369970723228411e+157 inf
3218 [-8.06819945e+157 -9.72060737e+158 -9.19485080e+154 -3.80929629e+154] -4.8999846830323085e+157 inf
3219 [9.04675483e+157 1.08995758e+159 1.03100526e+155 4.27130859e+154] 5.494281635876215e+157 inf
3220 [-1.01439948e+158 -1.22215360e+159 -1.15605122e+155 -4.78935626e+154] -6.160658174883612e+157 inf
3221 [1.13743139e+158 1.37038308e+159 1.29626344e+155 5.37023560e+154] 6.907856506650786e+157 inf
3222 [-1.27538530e+158 -1.53659063e+159 -1.45348136e+155 -6.02156715e+154] -7.745679140424005e+157 inf
3223 [1.43007100e+158 1.72295675e+159 1.62976753e+155 6.75189577e+154] 8.685117487405176e+157 inf
3224 [-1.60351784e+158 -1.93192638e+159 -1.82743466e+155 -7.57080263e+154] -9.738496057287468e+157 inf
3225 [1.79800126e+158 2.16624098e+159 2.04907593e+155 8.48903099e+154] 1.0919634143732864e+158 inf
3226 [-2.01607269e+158 -2.42897454e+159 -2.29759907e+155 -9.51862712e+154] -1.224402711995262e+158 inf
3227 [2.26059301e+158 2.72357386e+159 2.57626446e+155 1.06730983e+155] 1.3729049722803702e+158 inf
3228 [-2.53477010e+158 -3.05390380e+159 -2.88872791e+155 -1.19675901e+155] -1.5394183992296198e+158 inf
3229 [2.84220089e+158 3.42429796e+159 3.23908863e+155 1.34190849e+155] 1.7261274856849954e+158 inf
3230 [-3.18691857e+158 -3.83961555e+159 -3.63194303e+155 -1.50466249e+155] -1.9354816717327627e+158 inf
3231 [3.57344549e+158 4.30530514e+159 4.07244495e+155 1.68715619e+155] 2.1702274789552632e+158 inf
3232 [-4.00685251e+158 -4.82747610e+159 -4.56637335e+155 -1.89178372e+155] -2.433444542099892e+158 inf
3233 [4.49282551e+158 5.41297881e+159 5.12020810e+155 2.12122960e+155] 2.728586010866654e+158 inf
3234 [-5.03773997e+158 -6.06949450e+159 -5.74121495e+155 -2.37850394e+155] -3.05952385184525e+158 inf
3235 [5.64874463e+158 6.80563600e+159 6.43754092e+155 2.66698191e+155] 3.4305996449189005e+158 inf
3236 [-6.33385529e+158 -7.63106078e+159 -7.21832110e+155 -2.99044807e+155] -3.846681540534447e+158 inf
3237 [7.10205992e+158 8.55659758e+159 8.09379858e+155 3.35314597e+155] 4.3132281250608847e+158 inf
3238 [-7.96343660e+158 -9.59438855e+159 -9.07545876e+155 -3.75983386e+155] -4.836360032089359e+158 inf
3239 [8.92928576e+158 1.07580485e+160 1.01761801e+156 4.21584708e+155] 5.422940239141849e+158 inf
3240 [-1.00122784e+159 -1.20628435e+160 -1.14104028e+156 -4.72716809e+155] -6.080664103205593e+158 inf
3241 [1.12266223e+159 1.35258911e+160 1.27943189e+156 5.30050490e+155] 6.818160316268586e+158 inf
3242 [-1.25882485e+159 -1.51663852e+160 -1.43460839e+156 -5.94337913e+155] -7.645104105295454e+158 inf
3243 [1.41150201e+159 1.70058474e+160 1.60860555e+156 6.66422467e+155] 8.572344161715455e+158 inf
3244 [-1.58269670e+159 -1.90684096e+160 -1.80370603e+156 -7.47249830e+155] -9.612044965613698e+158 inf
3245 [1.77465482e+159 2.13811307e+160 2.02246937e+156 8.37880379e+155] 1.0777846371778174e+159 inf
3246 [-1.98989466e+159 -2.39743512e+160 -2.26776552e+156 -9.39503095e+155] -1.208504255121705e+159 inf
3247 [2.23123998e+159 2.68820917e+160 2.54281253e+156 1.05345117e+156] 1.3550782635680578e+159 inf
3248 [-2.50185697e+159 -3.01424989e+160 -2.85121875e+156 -1.18121949e+156] -1.5194295697450683e+159 inf
3249 [2.80529587e+159 3.37983460e+160 3.19703016e+156 1.32448426e+156] 1.7037143015907365e+159 inf
3250 [-3.14553750e+159 -3.78975944e+160 -3.58478347e+156 -1.48512495e+156] -1.9103500940368502e+159 inf
3251 [3.52704550e+159 4.24940220e+160 4.01956562e+156 1.66524903e+156] 2.1420478060078026e+159 inf
3252 [-3.95482488e+159 -4.76479295e+160 -4.50708053e+156 -1.86721955e+156] -2.401847084231034e+159 inf
3253 [4.43448768e+159 5.34269311e+160 5.05372392e+156 2.09368615e+156] 2.6931562404205443e+159 inf
3254 [-4.97232661e+159 -5.99068416e+160 -5.66666721e+156 -2.34761986e+156] -3.019796964983862e+159 inf
3255 [5.57539759e+159 6.71726711e+160 6.35395161e+156 2.63235205e+156] 3.3860544638515394e+159 inf
3256 [-6.25161231e+159 -7.53197402e+160 -7.12459363e+156 -2.95161811e+156] -3.796733676176255e+159 inf
3257 [7.00984206e+159 8.44549304e+160 7.98870333e+156 3.30960650e+156] 4.257222310421419e+159 inf
3258 [-7.86003406e+159 -9.46980865e+160 -8.95761698e+156 -3.71101369e+156] -4.7735615258120124e+159 inf
3259 [8.81334200e+159 1.06183589e+161 1.00440458e+157 4.16110573e+156] 5.3525251864184344e+159 inf
3260 [-9.88227234e+159 -1.19062115e+161 -1.12622426e+157 -4.66578740e+156] -6.001708727608693e+159 inf
3261 [1.10808484e+160 1.33502620e+161 1.26281890e+157 5.23167963e+156] 6.729628800711455e+159 inf
3262 [-1.24247943e+160 -1.49694548e+161 -1.41598049e+157 -5.86620636e+156] -7.545835003127434e+159 inf
3263 [1.39317414e+160 1.67850322e+161 1.58771835e+157 6.57769196e+156] 8.461035159681188e+159 inf
3264 [-1.56214592e+160 -1.88208127e+161 -1.78028552e+157 -7.37547043e+156] -9.487235798780453e+159 inf
3265 [1.75161152e+160 2.11035039e+161 1.99620829e+157 8.27000784e+156] 1.0637899666292561e+160 inf
3266 [-1.96405655e+160 -2.36630523e+161 -2.23831935e+157 -9.27303964e+156] -1.1928122343565325e+160 inf
3267 [2.20226808e+160 2.65330368e+161 2.50979497e+157 1.03977246e+157] 1.3374830286649054e+160 inf
3268 [-2.46937120e+160 -2.97511087e+161 -2.81419663e+157 -1.16588176e+157] -1.4997002884797348e+160 inf
3269 [2.76887005e+160 3.33594859e+161 3.15551780e+157 1.30728627e+157] 1.6815921451439024e+160 inf
3270 [-3.10469376e+160 -3.74055069e+161 -3.53823626e+157 -1.46584111e+157] -1.8855448414137617e+160 inf
3271 [3.48124800e+160 4.19422514e+161 3.96737292e+157 1.64362634e+157] 2.1142340366235386e+160 inf
3272 [-3.90347281e+160 -4.70292372e+161 -4.44855761e+157 -1.84297433e+157] -2.3706599087115553e+160 inf
3273 [4.37690735e+160 5.27332004e+161 4.98810302e+157 2.06650034e+157] 2.6581865136120277e+160 inf
3274 [-4.90776262e+160 -5.91289714e+161 -5.59308744e+157 -2.31713681e+157] -2.9805859183695754e+160 inf
3275 [5.50300293e+160 6.63004566e+161 6.27144769e+157 2.59817184e+157] 3.342087686958884e+160 inf
3276 [-6.17043723e+160 -7.43417388e+161 -7.03208318e+157 -2.91329234e+157] -3.747434368015896e+160 inf
3277 [6.91882162e+160 8.33583116e+161 7.88497271e+157 3.26663237e+157] 4.2019437124239155e+160 inf
3278 [-7.75797416e+160 -9.34684637e+161 -8.84130534e+157 -3.66282742e+157] -4.711578436990112e+160 inf
3279 [8.69890372e+160 1.04804830e+162 9.91362723e+157 4.10707517e+157] 5.2830244494408514e+160 inf
3280 [-9.75395436e+160 -1.17516134e+162 -1.11160062e+158 -4.60520372e+157] -5.923778560974177e+160 inf
3281 [1.09369673e+161 1.31769133e+162 1.24642162e+158 5.16374803e+157] 6.642246837069025e+160 inf
3282 [-1.22634625e+161 -1.47750815e+162 -1.39759446e+158 -5.79003564e+157] -7.447854876820031e+160 inf
3283 [1.37508424e+161 1.65670842e+162 1.56710236e+158 6.49228284e+157] 8.351171467552601e+160 inf
3284 [-1.54186198e+161 -1.85764308e+162 -1.75716911e+158 -7.27970243e+157] -9.364047236946404e+160 inf
3285 [1.72886744e+161 2.08294820e+162 1.97028819e+158 8.16262457e+157] 1.0499770121647597e+161 inf
3286 [-1.93855394e+161 -2.33557956e+162 -2.20925553e+158 -9.15263234e+157] -1.1773239691963824e+161 inf
3287 [2.17367237e+161 2.61885142e+162 2.47720612e+158 1.02627137e+158] 1.320116261961403e+161 inf
3288 [-2.43730724e+161 -2.93648005e+162 -2.77765524e+158 -1.15074317e+158] -1.4802271852873724e+161 inf
3289 [2.73291720e+161 3.29263242e+162 3.11454446e+158 1.29031160e+158] 1.6597572374484536e+161 inf
3290 [-3.06438036e+161 -3.69198090e+162 -3.49229346e+158 -1.44680765e+158] -1.8610616766422929e+161 inf
3291 [3.43604517e+161 4.13976454e+162 3.91585791e+158 1.62228440e+158] 2.0867814196678707e+161 inf
3292 [-3.85278753e+161 -4.64185783e+162 -4.39079459e+158 -1.81904393e+158] -2.339877688163257e+161 inf

C:\Users\alirm\AppData\Local\Temp\ipykernel_55216\3740082756.py:20: RuntimeWarning: overflow encountered in scalar add
  dj_dw[j] += (y_hat - y_train[i]) * X_train[i, j]
C:\Users\alirm\AppData\Local\Temp\ipykernel_55216\3740082756.py:20: RuntimeWarning: invalid value encountered in scalar multiply
  dj_dw[j] += (y_hat - y_train[i]) * X_train[i, j]
C:\Users\alirm\AppData\Local\Temp\ipykernel_55216\3740082756.py:9: RuntimeWarning: invalid value encountered in subtract
  w = w - learning_rate * dj_dw

6139 [nan nan nan nan] nan nan
6140 [nan nan nan nan] nan nan
6141 [nan nan nan nan] nan nan
6142 [nan nan nan nan] nan nan
6143 [nan nan nan nan] nan nan
6144 [nan nan nan nan] nan nan
6145 [nan nan nan nan] nan nan
6146 [nan nan nan nan] nan nan
6147 [nan nan nan nan] nan nan
6148 [nan nan nan nan] nan nan
6149 [nan nan nan nan] nan nan
6150 [nan nan nan nan] nan nan
6151 [nan nan nan nan] nan nan
6152 [nan nan nan nan] nan nan
6153 [nan nan nan nan] nan nan
6154 [nan nan nan nan] nan nan
6155 [nan nan nan nan] nan nan
6156 [nan nan nan nan] nan nan
6157 [nan nan nan nan] nan nan
6158 [nan nan nan nan] nan nan
6159 [nan nan nan nan] nan nan
6160 [nan nan nan nan] nan nan
6161 [nan nan nan nan] nan nan
6162 [nan nan nan nan] nan nan
6163 [nan nan nan nan] nan nan
6164 [nan nan nan nan] nan nan
6165 [nan nan nan nan] nan nan
6166 [nan nan nan nan] nan nan
6167 [nan nan nan nan] nan nan
6168 [nan nan nan nan] nan nan
6169 [nan nan nan nan] nan nan
6170 [nan nan nan nan] nan nan
6171 [nan nan nan nan] nan nan
6172 [nan nan nan nan] nan nan
6173 [nan nan nan nan] nan nan
6174 [nan nan nan nan] nan nan
6175 [nan nan nan nan] nan nan
6176 [nan nan nan nan] nan nan
6177 [nan nan nan nan] nan nan
6178 [nan nan nan nan] nan nan
6179 [nan nan nan nan] nan nan
6180 [nan nan nan nan] nan nan
6181 [nan nan nan nan] nan nan
6182 [nan nan nan nan] nan nan
6183 [nan nan nan nan] nan nan
6184 [nan nan nan nan] nan nan
6185 [nan nan nan nan] nan nan
6186 [nan nan nan nan] nan nan
6187 [nan nan nan nan] nan nan
6188 [nan nan nan nan] nan nan
6189 [nan nan nan nan] nan nan
6190 [nan nan nan nan] nan nan
6191 [nan nan nan nan] nan nan
6192 [nan nan nan nan] nan nan
6193 [nan nan nan nan] nan nan
6194 [nan nan nan nan] nan nan
6195 [nan nan nan nan] nan nan
6196 [nan nan nan nan] nan nan
6197 [nan nan nan nan] nan nan
6198 [nan nan nan nan] nan nan
6199 [nan nan nan nan] nan nan
6200 [nan nan nan nan] nan nan
6201 [nan nan nan nan] nan nan
6202 [nan nan nan nan] nan nan
6203 [nan nan nan nan] nan nan
6204 [nan nan nan nan] nan nan
6205 [nan nan nan nan] nan nan
6206 [nan nan nan nan] nan nan
6207 [nan nan nan nan] nan nan
6208 [nan nan nan nan] nan nan
6209 [nan nan nan nan] nan nan
6210 [nan nan nan nan] nan nan
6211 [nan nan nan nan] nan nan
6212 [nan nan nan nan] nan nan
6213 [nan nan nan nan] nan nan
6214 [nan nan nan nan] nan nan
6215 [nan nan nan nan] nan nan
6216 [nan nan nan nan] nan nan
6217 [nan nan nan nan] nan nan
6218 [nan nan nan nan] nan nan
6219 [nan nan nan nan] nan nan
6220 [nan nan nan nan] nan nan
6221 [nan nan nan nan] nan nan
6222 [nan nan nan nan] nan nan
6223 [nan nan nan nan] nan nan
6224 [nan nan nan nan] nan nan
6225 [nan nan nan nan] nan nan
6226 [nan nan nan nan] nan nan
6227 [nan nan nan nan] nan nan
6228 [nan nan nan nan] nan nan
6229 [nan nan nan nan] nan nan
6230 [nan nan nan nan] nan nan
6231 [nan nan nan nan] nan nan
6232 [nan nan nan nan] nan nan
6233 [nan nan nan nan] nan nan
6234 [nan nan nan nan] nan nan
6235 [nan nan nan nan] nan nan
6236 [nan nan nan nan] nan nan
6237 [nan nan nan nan] nan nan
6238 [nan nan nan nan] nan nan
6239 [nan nan nan nan] nan nan
6240 [nan nan nan nan] nan nan
6241 [nan nan nan nan] nan nan
6242 [nan nan nan nan] nan nan
6243 [nan nan nan nan] nan nan
6244 [nan nan nan nan] nan nan
6245 [nan nan nan nan] nan nan
6246 [nan nan nan nan] nan nan
6247 [nan nan nan nan] nan nan
6248 [nan nan nan nan] nan nan
6249 [nan nan nan nan] nan nan
6250 [nan nan nan nan] nan nan
6251 [nan nan nan nan] nan nan
6252 [nan nan nan nan] nan nan
6253 [nan nan nan nan] nan nan
6254 [nan nan nan nan] nan nan
6255 [nan nan nan nan] nan nan
6256 [nan nan nan nan] nan nan
6257 [nan nan nan nan] nan nan
6258 [nan nan nan nan] nan nan
6259 [nan nan nan nan] nan nan
6260 [nan nan nan nan] nan nan
6261 [nan nan nan nan] nan nan
6262 [nan nan nan nan] nan nan
6263 [nan nan nan nan] nan nan
6264 [nan nan nan nan] nan nan
6265 [nan nan nan nan] nan nan
6266 [nan nan nan nan] nan nan
6267 [nan nan nan nan] nan nan
6268 [nan nan nan nan] nan nan
6269 [nan nan nan nan] nan nan
6270 [nan nan nan nan] nan nan
6271 [nan nan nan nan] nan nan
6272 [nan nan nan nan] nan nan
6273 [nan nan nan nan] nan nan
6274 [nan nan nan nan] nan nan
6275 [nan nan nan nan] nan nan
6276 [nan nan nan nan] nan nan
6277 [nan nan nan nan] nan nan
6278 [nan nan nan nan] nan nan
6279 [nan nan nan nan] nan nan
6280 [nan nan nan nan] nan nan
6281 [nan nan nan nan] nan nan
6282 [nan nan nan nan] nan nan
6283 [nan nan nan nan] nan nan
6284 [nan nan nan nan] nan nan
6285 [nan nan nan nan] nan nan
6286 [nan nan nan nan] nan nan
6287 [nan nan nan nan] nan nan
6288 [nan nan nan nan] nan nan
6289 [nan nan nan nan] nan nan
6290 [nan nan nan nan] nan nan
6291 [nan nan nan nan] nan nan
6292 [nan nan nan nan] nan nan
6293 [nan nan nan nan] nan nan
6294 [nan nan nan nan] nan nan
6295 [nan nan nan nan] nan nan
6296 [nan nan nan nan] nan nan
6297 [nan nan nan nan] nan nan
6298 [nan nan nan nan] nan nan
6299 [nan nan nan nan] nan nan
6300 [nan nan nan nan] nan nan
6301 [nan nan nan nan] nan nan
6302 [nan nan nan nan] nan nan
6303 [nan nan nan nan] nan nan
6304 [nan nan nan nan] nan nan
6305 [nan nan nan nan] nan nan
6306 [nan nan nan nan] nan nan
6307 [nan nan nan nan] nan nan
6308 [nan nan nan nan] nan nan
6309 [nan nan nan nan] nan nan
6310 [nan nan nan nan] nan nan
6311 [nan nan nan nan] nan nan
6312 [nan nan nan nan] nan nan
6313 [nan nan nan nan] nan nan
6314 [nan nan nan nan] nan nan
6315 [nan nan nan nan] nan nan
6316 [nan nan nan nan] nan nan
6317 [nan nan nan nan] nan nan
6318 [nan nan nan nan] nan nan
6319 [nan nan nan nan] nan nan
6320 [nan nan nan nan] nan nan
6321 [nan nan nan nan] nan nan
6322 [nan nan nan nan] nan nan
6323 [nan nan nan nan] nan nan
6324 [nan nan nan nan] nan nan
6325 [nan nan nan nan] nan nan
6326 [nan nan nan nan] nan nan
6327 [nan nan nan nan] nan nan
6328 [nan nan nan nan] nan nan
6329 [nan nan nan nan] nan nan
6330 [nan nan nan nan] nan nan
6331 [nan nan nan nan] nan nan
6332 [nan nan nan nan] nan nan
6333 [nan nan nan nan] nan nan
6334 [nan nan nan nan] nan nan
6335 [nan nan nan nan] nan nan
6336 [nan nan nan nan] nan nan
6337 [nan nan nan nan] nan nan
6338 [nan nan nan nan] nan nan
6339 [nan nan nan nan] nan nan
6340 [nan nan nan nan] nan nan
6341 [nan nan nan nan] nan nan
6342 [nan nan nan nan] nan nan
6343 [nan nan nan nan] nan nan
6344 [nan nan nan nan] nan nan
6345 [nan nan nan nan] nan nan
6346 [nan nan nan nan] nan nan
6347 [nan nan nan nan] nan nan
6348 [nan nan nan nan] nan nan
6349 [nan nan nan nan] nan nan
6350 [nan nan nan nan] nan nan
6351 [nan nan nan nan] nan nan
6352 [nan nan nan nan] nan nan
6353 [nan nan nan nan] nan nan
6354 [nan nan nan nan] nan nan
6355 [nan nan nan nan] nan nan
6356 [nan nan nan nan] nan nan
6357 [nan nan nan nan] nan nan
6358 [nan nan nan nan] nan nan
6359 [nan nan nan nan] nan nan
6360 [nan nan nan nan] nan nan
6361 [nan nan nan nan] nan nan
6362 [nan nan nan nan] nan nan
6363 [nan nan nan nan] nan nan
6364 [nan nan nan nan] nan nan
6365 [nan nan nan nan] nan nan
6366 [nan nan nan nan] nan nan
6367 [nan nan nan nan] nan nan
6368 [nan nan nan nan] nan nan
6369 [nan nan nan nan] nan nan
6370 [nan nan nan nan] nan nan
6371 [nan nan nan nan] nan nan
6372 [nan nan nan nan] nan nan
6373 [nan nan nan nan] nan nan
6374 [nan nan nan nan] nan nan
6375 [nan nan nan nan] nan nan
6376 [nan nan nan nan] nan nan
6377 [nan nan nan nan] nan nan
6378 [nan nan nan nan] nan nan
6379 [nan nan nan nan] nan nan
6380 [nan nan nan nan] nan nan
6381 [nan nan nan nan] nan nan
6382 [nan nan nan nan] nan nan
6383 [nan nan nan nan] nan nan
6384 [nan nan nan nan] nan nan
6385 [nan nan nan nan] nan nan
6386 [nan nan nan nan] nan nan
6387 [nan nan nan nan] nan nan
6388 [nan nan nan nan] nan nan
6389 [nan nan nan nan] nan nan
6390 [nan nan nan nan] nan nan
6391 [nan nan nan nan] nan nan
6392 [nan nan nan nan] nan nan
6393 [nan nan nan nan] nan nan
6394 [nan nan nan nan] nan nan
6395 [nan nan nan nan] nan nan
6396 [nan nan nan nan] nan nan
6397 [nan nan nan nan] nan nan
6398 [nan nan nan nan] nan nan
6399 [nan nan nan nan] nan nan
6400 [nan nan nan nan] nan nan
6401 [nan nan nan nan] nan nan
6402 [nan nan nan nan] nan nan
6403 [nan nan nan nan] nan nan
6404 [nan nan nan nan] nan nan
6405 [nan nan nan nan] nan nan
6406 [nan nan nan nan] nan nan
6407 [nan nan nan nan] nan nan
6408 [nan nan nan nan] nan nan
6409 [nan nan nan nan] nan nan
6410 [nan nan nan nan] nan nan
6411 [nan nan nan nan] nan nan
6412 [nan nan nan nan] nan nan
6413 [nan nan nan nan] nan nan
6414 [nan nan nan nan] nan nan
6415 [nan nan nan nan] nan nan
6416 [nan nan nan nan] nan nan
6417 [nan nan nan nan] nan nan
6418 [nan nan nan nan] nan nan
6419 [nan nan nan nan] nan nan
6420 [nan nan nan nan] nan nan
6421 [nan nan nan nan] nan nan
6422 [nan nan nan nan] nan nan
6423 [nan nan nan nan] nan nan
6424 [nan nan nan nan] nan nan
6425 [nan nan nan nan] nan nan
6426 [nan nan nan nan] nan nan
6427 [nan nan nan nan] nan nan
6428 [nan nan nan nan] nan nan
6429 [nan nan nan nan] nan nan
6430 [nan nan nan nan] nan nan
6431 [nan nan nan nan] nan nan
6432 [nan nan nan nan] nan nan
6433 [nan nan nan nan] nan nan
6434 [nan nan nan nan] nan nan
6435 [nan nan nan nan] nan nan
6436 [nan nan nan nan] nan nan
6437 [nan nan nan nan] nan nan
6438 [nan nan nan nan] nan nan
6439 [nan nan nan nan] nan nan
6440 [nan nan nan nan] nan nan
6441 [nan nan nan nan] nan nan
6442 [nan nan nan nan] nan nan
6443 [nan nan nan nan] nan nan
6444 [nan nan nan nan] nan nan
6445 [nan nan nan nan] nan nan
6446 [nan nan nan nan] nan nan
6447 [nan nan nan nan] nan nan
6448 [nan nan nan nan] nan nan
6449 [nan nan nan nan] nan nan
6450 [nan nan nan nan] nan nan
6451 [nan nan nan nan] nan nan
6452 [nan nan nan nan] nan nan
6453 [nan nan nan nan] nan nan
6454 [nan nan nan nan] nan nan
6455 [nan nan nan nan] nan nan
6456 [nan nan nan nan] nan nan
6457 [nan nan nan nan] nan nan
6458 [nan nan nan nan] nan nan
6459 [nan nan nan nan] nan nan
6460 [nan nan nan nan] nan nan
6461 [nan nan nan nan] nan nan
6462 [nan nan nan nan] nan nan
6463 [nan nan nan nan] nan nan
6464 [nan nan nan nan] nan nan
6465 [nan nan nan nan] nan nan
6466 [nan nan nan nan] nan nan
6467 [nan nan nan nan] nan nan
6468 [nan nan nan nan] nan nan
6469 [nan nan nan nan] nan nan
6470 [nan nan nan nan] nan nan
6471 [nan nan nan nan] nan nan
6472 [nan nan nan nan] nan nan
6473 [nan nan nan nan] nan nan
6474 [nan nan nan nan] nan nan
6475 [nan nan nan nan] nan nan
6476 [nan nan nan nan] nan nan
6477 [nan nan nan nan] nan nan
6478 [nan nan nan nan] nan nan
6479 [nan nan nan nan] nan nan
6480 [nan nan nan nan] nan nan
6481 [nan nan nan nan] nan nan
6482 [nan nan nan nan] nan nan
6483 [nan nan nan nan] nan nan
6484 [nan nan nan nan] nan nan
6485 [nan nan nan nan] nan nan
6486 [nan nan nan nan] nan nan
6487 [nan nan nan nan] nan nan
6488 [nan nan nan nan] nan nan
6489 [nan nan nan nan] nan nan
6490 [nan nan nan nan] nan nan
6491 [nan nan nan nan] nan nan
6492 [nan nan nan nan] nan nan
6493 [nan nan nan nan] nan nan
6494 [nan nan nan nan] nan nan
6495 [nan nan nan nan] nan nan
6496 [nan nan nan nan] nan nan
6497 [nan nan nan nan] nan nan
6498 [nan nan nan nan] nan nan
6499 [nan nan nan nan] nan nan
6500 [nan nan nan nan] nan nan
6501 [nan nan nan nan] nan nan
6502 [nan nan nan nan] nan nan
6503 [nan nan nan nan] nan nan
6504 [nan nan nan nan] nan nan
6505 [nan nan nan nan] nan nan
6506 [nan nan nan nan] nan nan
6507 [nan nan nan nan] nan nan
6508 [nan nan nan nan] nan nan
6509 [nan nan nan nan] nan nan
6510 [nan nan nan nan] nan nan
6511 [nan nan nan nan] nan nan
6512 [nan nan nan nan] nan nan
6513 [nan nan nan nan] nan nan
6514 [nan nan nan nan] nan nan
6515 [nan nan nan nan] nan nan
6516 [nan nan nan nan] nan nan
6517 [nan nan nan nan] nan nan
6518 [nan nan nan nan] nan nan
6519 [nan nan nan nan] nan nan
6520 [nan nan nan nan] nan nan
6521 [nan nan nan nan] nan nan
6522 [nan nan nan nan] nan nan
6523 [nan nan nan nan] nan nan
6524 [nan nan nan nan] nan nan
6525 [nan nan nan nan] nan nan
6526 [nan nan nan nan] nan nan
6527 [nan nan nan nan] nan nan
6528 [nan nan nan nan] nan nan
6529 [nan nan nan nan] nan nan
6530 [nan nan nan nan] nan nan
6531 [nan nan nan nan] nan nan
6532 [nan nan nan nan] nan nan
6533 [nan nan nan nan] nan nan
6534 [nan nan nan nan] nan nan
6535 [nan nan nan nan] nan nan
6536 [nan nan nan nan] nan nan
6537 [nan nan nan nan] nan nan
6538 [nan nan nan nan] nan nan
6539 [nan nan nan nan] nan nan
6540 [nan nan nan nan] nan nan
6541 [nan nan nan nan] nan nan
6542 [nan nan nan nan] nan nan
6543 [nan nan nan nan] nan nan
6544 [nan nan nan nan] nan nan
6545 [nan nan nan nan] nan nan
6546 [nan nan nan nan] nan nan
6547 [nan nan nan nan] nan nan
6548 [nan nan nan nan] nan nan
6549 [nan nan nan nan] nan nan
6550 [nan nan nan nan] nan nan
6551 [nan nan nan nan] nan nan
6552 [nan nan nan nan] nan nan
6553 [nan nan nan nan] nan nan
6554 [nan nan nan nan] nan nan
6555 [nan nan nan nan] nan nan
6556 [nan nan nan nan] nan nan
6557 [nan nan nan nan] nan nan
6558 [nan nan nan nan] nan nan
6559 [nan nan nan nan] nan nan
6560 [nan nan nan nan] nan nan
6561 [nan nan nan nan] nan nan
6562 [nan nan nan nan] nan nan
6563 [nan nan nan nan] nan nan
6564 [nan nan nan nan] nan nan
6565 [nan nan nan nan] nan nan
6566 [nan nan nan nan] nan nan
6567 [nan nan nan nan] nan nan
6568 [nan nan nan nan] nan nan
6569 [nan nan nan nan] nan nan
6570 [nan nan nan nan] nan nan
6571 [nan nan nan nan] nan nan
6572 [nan nan nan nan] nan nan
6573 [nan nan nan nan] nan nan
6574 [nan nan nan nan] nan nan
6575 [nan nan nan nan] nan nan
6576 [nan nan nan nan] nan nan
6577 [nan nan nan nan] nan nan
6578 [nan nan nan nan] nan nan
6579 [nan nan nan nan] nan nan
6580 [nan nan nan nan] nan nan
6581 [nan nan nan nan] nan nan
6582 [nan nan nan nan] nan nan
6583 [nan nan nan nan] nan nan
6584 [nan nan nan nan] nan nan
6585 [nan nan nan nan] nan nan
6586 [nan nan nan nan] nan nan
6587 [nan nan nan nan] nan nan
6588 [nan nan nan nan] nan nan
6589 [nan nan nan nan] nan nan
6590 [nan nan nan nan] nan nan
6591 [nan nan nan nan] nan nan
6592 [nan nan nan nan] nan nan
6593 [nan nan nan nan] nan nan
6594 [nan nan nan nan] nan nan
6595 [nan nan nan nan] nan nan
6596 [nan nan nan nan] nan nan
6597 [nan nan nan nan] nan nan
6598 [nan nan nan nan] nan nan
6599 [nan nan nan nan] nan nan
6600 [nan nan nan nan] nan nan
6601 [nan nan nan nan] nan nan
6602 [nan nan nan nan] nan nan
6603 [nan nan nan nan] nan nan
6604 [nan nan nan nan] nan nan
6605 [nan nan nan nan] nan nan
6606 [nan nan nan nan] nan nan
6607 [nan nan nan nan] nan nan
6608 [nan nan nan nan] nan nan
6609 [nan nan nan nan] nan nan
6610 [nan nan nan nan] nan nan
6611 [nan nan nan nan] nan nan
6612 [nan nan nan nan] nan nan
6613 [nan nan nan nan] nan nan
6614 [nan nan nan nan] nan nan
6615 [nan nan nan nan] nan nan
6616 [nan nan nan nan] nan nan
6617 [nan nan nan nan] nan nan
6618 [nan nan nan nan] nan nan
6619 [nan nan nan nan] nan nan
6620 [nan nan nan nan] nan nan
6621 [nan nan nan nan] nan nan
6622 [nan nan nan nan] nan nan
6623 [nan nan nan nan] nan nan
6624 [nan nan nan nan] nan nan
6625 [nan nan nan nan] nan nan
6626 [nan nan nan nan] nan nan
6627 [nan nan nan nan] nan nan
6628 [nan nan nan nan] nan nan
6629 [nan nan nan nan] nan nan
6630 [nan nan nan nan] nan nan
6631 [nan nan nan nan] nan nan
6632 [nan nan nan nan] nan nan
6633 [nan nan nan nan] nan nan
6634 [nan nan nan nan] nan nan
6635 [nan nan nan nan] nan nan
6636 [nan nan nan nan] nan nan
6637 [nan nan nan nan] nan nan
6638 [nan nan nan nan] nan nan
6639 [nan nan nan nan] nan nan
6640 [nan nan nan nan] nan nan
6641 [nan nan nan nan] nan nan
6642 [nan nan nan nan] nan nan
6643 [nan nan nan nan] nan nan
6644 [nan nan nan nan] nan nan
6645 [nan nan nan nan] nan nan
6646 [nan nan nan nan] nan nan
6647 [nan nan nan nan] nan nan
6648 [nan nan nan nan] nan nan
6649 [nan nan nan nan] nan nan
6650 [nan nan nan nan] nan nan
6651 [nan nan nan nan] nan nan
6652 [nan nan nan nan] nan nan
6653 [nan nan nan nan] nan nan
6654 [nan nan nan nan] nan nan
6655 [nan nan nan nan] nan nan
6656 [nan nan nan nan] nan nan
6657 [nan nan nan nan] nan nan
6658 [nan nan nan nan] nan nan
6659 [nan nan nan nan] nan nan
6660 [nan nan nan nan] nan nan
6661 [nan nan nan nan] nan nan
6662 [nan nan nan nan] nan nan
6663 [nan nan nan nan] nan nan
6664 [nan nan nan nan] nan nan
6665 [nan nan nan nan] nan nan
6666 [nan nan nan nan] nan nan
6667 [nan nan nan nan] nan nan
6668 [nan nan nan nan] nan nan
6669 [nan nan nan nan] nan nan
6670 [nan nan nan nan] nan nan
6671 [nan nan nan nan] nan nan
6672 [nan nan nan nan] nan nan
6673 [nan nan nan nan] nan nan
6674 [nan nan nan nan] nan nan
6675 [nan nan nan nan] nan nan
6676 [nan nan nan nan] nan nan
6677 [nan nan nan nan] nan nan
6678 [nan nan nan nan] nan nan
6679 [nan nan nan nan] nan nan
6680 [nan nan nan nan] nan nan
6681 [nan nan nan nan] nan nan
6682 [nan nan nan nan] nan nan
6683 [nan nan nan nan] nan nan
6684 [nan nan nan nan] nan nan
6685 [nan nan nan nan] nan nan
6686 [nan nan nan nan] nan nan
6687 [nan nan nan nan] nan nan
6688 [nan nan nan nan] nan nan
6689 [nan nan nan nan] nan nan
6690 [nan nan nan nan] nan nan
6691 [nan nan nan nan] nan nan
6692 [nan nan nan nan] nan nan
6693 [nan nan nan nan] nan nan
6694 [nan nan nan nan] nan nan
6695 [nan nan nan nan] nan nan
6696 [nan nan nan nan] nan nan
6697 [nan nan nan nan] nan nan
6698 [nan nan nan nan] nan nan
6699 [nan nan nan nan] nan nan
6700 [nan nan nan nan] nan nan
6701 [nan nan nan nan] nan nan
6702 [nan nan nan nan] nan nan
6703 [nan nan nan nan] nan nan
6704 [nan nan nan nan] nan nan
6705 [nan nan nan nan] nan nan
6706 [nan nan nan nan] nan nan
6707 [nan nan nan nan] nan nan
6708 [nan nan nan nan] nan nan
6709 [nan nan nan nan] nan nan
6710 [nan nan nan nan] nan nan
6711 [nan nan nan nan] nan nan
6712 [nan nan nan nan] nan nan
6713 [nan nan nan nan] nan nan
6714 [nan nan nan nan] nan nan
6715 [nan nan nan nan] nan nan
6716 [nan nan nan nan] nan nan
6717 [nan nan nan nan] nan nan
6718 [nan nan nan nan] nan nan
6719 [nan nan nan nan] nan nan
6720 [nan nan nan nan] nan nan
6721 [nan nan nan nan] nan nan
6722 [nan nan nan nan] nan nan
6723 [nan nan nan nan] nan nan
6724 [nan nan nan nan] nan nan
6725 [nan nan nan nan] nan nan
6726 [nan nan nan nan] nan nan
6727 [nan nan nan nan] nan nan
6728 [nan nan nan nan] nan nan
6729 [nan nan nan nan] nan nan
6730 [nan nan nan nan] nan nan
6731 [nan nan nan nan] nan nan
6732 [nan nan nan nan] nan nan
6733 [nan nan nan nan] nan nan
6734 [nan nan nan nan] nan nan
6735 [nan nan nan nan] nan nan
6736 [nan nan nan nan] nan nan
6737 [nan nan nan nan] nan nan
6738 [nan nan nan nan] nan nan
6739 [nan nan nan nan] nan nan
6740 [nan nan nan nan] nan nan
6741 [nan nan nan nan] nan nan
6742 [nan nan nan nan] nan nan
6743 [nan nan nan nan] nan nan
6744 [nan nan nan nan] nan nan
6745 [nan nan nan nan] nan nan
6746 [nan nan nan nan] nan nan
6747 [nan nan nan nan] nan nan
6748 [nan nan nan nan] nan nan
6749 [nan nan nan nan] nan nan
6750 [nan nan nan nan] nan nan
6751 [nan nan nan nan] nan nan
6752 [nan nan nan nan] nan nan
6753 [nan nan nan nan] nan nan
6754 [nan nan nan nan] nan nan
6755 [nan nan nan nan] nan nan
6756 [nan nan nan nan] nan nan
6757 [nan nan nan nan] nan nan
6758 [nan nan nan nan] nan nan
6759 [nan nan nan nan] nan nan
6760 [nan nan nan nan] nan nan
6761 [nan nan nan nan] nan nan
6762 [nan nan nan nan] nan nan
6763 [nan nan nan nan] nan nan
6764 [nan nan nan nan] nan nan
6765 [nan nan nan nan] nan nan
6766 [nan nan nan nan] nan nan
6767 [nan nan nan nan] nan nan
6768 [nan nan nan nan] nan nan
6769 [nan nan nan nan] nan nan
6770 [nan nan nan nan] nan nan
6771 [nan nan nan nan] nan nan
6772 [nan nan nan nan] nan nan
6773 [nan nan nan nan] nan nan
6774 [nan nan nan nan] nan nan
6775 [nan nan nan nan] nan nan
6776 [nan nan nan nan] nan nan
6777 [nan nan nan nan] nan nan
6778 [nan nan nan nan] nan nan
6779 [nan nan nan nan] nan nan
6780 [nan nan nan nan] nan nan
6781 [nan nan nan nan] nan nan
6782 [nan nan nan nan] nan nan
6783 [nan nan nan nan] nan nan

In [84]:
x_valid = validation_rows['GrLivArea'].to_numpy() / 1000
y_valid = validation_rows['SalePrice'].to_numpy() / 1000

sse = 0
valid_y_hat = []
for i in range(len(x_valid)):
    y_hat = func(x_valid[i], best_w, best_b)
    sse += (y_hat - y_valid[i])**2
    valid_y_hat.append(y_hat * 1000)

m = len(x_valid)
cost = ( 1 / (2 * m)) * sse

print('cost: ', cost)

NameError: name 'validation_rows' is not defined

In [ ]:
# validation_rows['PredictedSales'] = predictions * 1000
validation_rows['PredictedSales'] = valid_y_hat

C:\Users\alirm\AppData\Local\Temp\ipykernel_65228\3410635853.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  validation_rows['PredictedSales'] = valid_y_hat

In [ ]:
test_rows = pd.read_csv('test.csv')[['Id', 'GrLivArea']]
test_rows.head()

     Id  GrLivArea
0  1461        896
1  1462       1329
2  1463       1629
3  1464       1604
4  1465       1280

In [ ]:
x_test = test_rows['GrLivArea'].to_numpy() / 1000
predictions = best_w * x_test + best_b

test_rows['SalePrice'] = predictions * 1000
test_rows

        Id  GrLivArea      SalePrice
0     1461        896  153947.934988
1     1462       1329  185671.186752
2     1463       1629  207650.345018
3     1464       1604  205818.748496
4     1465       1280  182081.257569
...    ...        ...            ...
1454  2915       1092  168307.651722
1455  2916       1092  168307.651722
1456  2917       1224  177978.481359
1457  2918        970  159369.460694
1458  2919       2000  234831.237407

[1459 rows x 3 columns]

In [ ]:
test_rows[['Id', 'SalePrice']].to_csv('submission.csv', index=False)

In [ ]:
# Use the direct formula method
import numpy as np

test_rows = pd.read_csv('test.csv')[['Id', 'GrLivArea']]
x_mean = x_train.mean()
y_mean = y_train.mean()

best_w_dir = np.sum((x_train - x_mean) * (y_train - y_mean)) / np.sum((x_train - x_mean)**2)
best_b_dir = y_mean - best_w_dir * x_mean

predictions = best_w_dir * x_test + best_b_dir
test_rows['SalePrice'] = predictions * 1000

print(best_b_dir, best_w_dir)

88.30358211933743 73.26381959688686

In [ ]:
test_rows[['Id', 'SalePrice']].to_csv('submission_dir.csv', index=False)